---
title: "10 year without ICICLE"
output: html_document
date: '2022-10-13'
---

```{r 10 years model}

imp3.new10<-imp3.new%>%
  filter(clus!="ICICLE")

imp3.new10%>%
  filter(cens==1)%>%  #cens==1 event
  summarise(max(year),min(year))
  
PO0.10<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal+clus,data=imp3.new10,k=0,scale = "odds") #log-logistic model

PO1.10<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal+clus,data=imp3.new10,k=1,bknots = c(log(0.1067762),log(9.943874)),scale = "odds")

PO2.10<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal+clus,data=imp3.new10,k=2,bknots = c(log(0.1067762),log(9.943874)),scale = "odds")

PH0.10<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal+clus,data=imp3.new10,k=0,scale = "hazard")

PH1.10<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal+clus,data=imp3.new10,k=1,bknots = c(log(0.1067762),log(9.943874)),scale = "hazard")

PH2.10<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal+clus,data=imp3.new10,k=2,bknots = c(log(0.1067762),log(9.943874)),scale = "hazard")
```


```{r POPH compare 10 years}

AIC(PO0.10) 
AIC(PO1.10) #1 knots in median
AIC(PO2.10) #2 knots one in 33% one in 67%

BIC(PO0.10) 
BIC(PO1.10) #1 knots in median
BIC(PO2.10) #2 knots one in 33% one in 67%


AIC(PH0.10) 
AIC(PH1.10) #1 knots in median
AIC(PH2.10) #2 knots one in 33% one in 67%

BIC(PH0.10) 
BIC(PH1.10) #1 knots in median
BIC(PH2.10) #2 knots one in 33% one in 67%

#same the final is PO1
```


```{r censor for 10 years}

imp3.temp10<-survSplit(Surv(year, cens) ~ ., data = imp3.new10, cut = 10,
                  episode="timegroup")
imp3.10y<-subset(imp3.temp10, timegroup == 1) #only the first 10 year
```

```{r Harrell Uno 10 years}

#---leave CamPalGN out----

data10y.1<-imp3.10y%>%
  filter(clus!="CamPalGN")

data10y.1v<-imp3.10y%>%
  filter(clus=="CamPalGN")

#Boundary knots location
data10y.1%>%
  filter(cens==1)%>%  #cens==1 event
  summarise(max(year),min(year))  


#refit model
model1.10<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl,data=data10y.1,k=1,bknots = c(log(0.1067762),log(9.943874)),scale = "odds")

#linear predictor

h0.1.10<-predict(model1.10,newdata = data10y.1v,type="hazard",times=10)  #H0(t=10)
h.1.10<-predict(model1.10,newdata = data10y.1v,type="cumhaz",times=10)   #H(t=10)

lp.1.10<-log((exp(h.1.10[[2]])-1)/(exp(h0.1.10[[2]])-1))


#add linear predictor in validation datasets


data10y.1v$lp.1.10<-lp.1.10 #It is the same as lp!!!

# Harrell's C
harrell_C_1v.10 <- concordance(Surv(year,cens) ~ lp.1.10, 
                              data10y.1v, 
                               reverse = TRUE)
# Uno's C
Uno_C_1v.10<- concordance(Surv(year,cens) ~ lp.1.10, 
                           data10y.1v, 
                           reverse = TRUE,
                           timewt = "n/G2")

#---leave NYPUM out----

data10y.3<-imp3.10y%>%
  filter(clus!="NYPUM")

data10y.3v<-imp3.10y%>%
  filter(clus=="NYPUM")

#Boundary knots location
data10y.3%>%
  filter(cens==1)%>%  #cens==1 event
  summarise(max(year),min(year))  

#refit model
model3.10<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl,data=data10y.3,k=1,bknots = c(log(0.1067762),log(9.943874)),scale = "odds")

#linear predictor

h0.3.10<-predict(model3.10,newdata = data10y.3v,type="hazard",times=10)  #H0(t=10)
h.3.10<-predict(model3.10,newdata = data10y.3v,type="cumhaz",times=10)   #H(t=10)

lp.3.10<-log((exp(h.3.10[[2]])-1)/(exp(h0.3.10[[2]])-1))


#add linear predictor in validation datasets

data10y.3v$lp.3.10<-lp.3.10 


# Harrell's C
harrell_C_3v.10 <- concordance(Surv(year,cens) ~ lp.3.10, 
                              data10y.3v, 
                               reverse = TRUE)
# Uno's C
Uno_C_3v.10<- concordance(Surv(year,cens) ~ lp.3.10, 
                           data10y.3v, 
                           reverse = TRUE,
                           timewt = "n/G2")


#---leave ParkWest out----

data10y.4<-imp3.10y%>%
  filter(clus!="ParkWest")

data10y.4v<-imp3.10y%>%
  filter(clus=="ParkWest")

#Boundary knots location
data10y.4%>%
  filter(cens==1)%>%  #cens==1 event
  summarise(max(year),min(year))  

#refit model
model4.10<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl,data=data10y.4,k=1,bknots = c(log(0.1067762),log(9.943874	)),scale = "odds")

h0.4.10<-predict(model4.10,newdata = data10y.4v,type="hazard",times=10)  #H0(t=10)
h.4.10<-predict(model4.10,newdata = data10y.4v,type="cumhaz",times=10)   #H(t=10)

lp.4.10<-log((exp(h.4.10[[2]])-1)/(exp(h0.4.10[[2]])-1))


#add linear predictor in validation datasets

data10y.4v$lp.4.10<-lp.4.10 

# Harrell's C
harrell_C_4v.10 <- concordance(Surv(year,cens) ~ lp.4.10, 
                              data10y.4v, 
                               reverse = TRUE)
# Uno's C
Uno_C_4v.10<- concordance(Surv(year,cens) ~ lp.4.10, 
                           data10y.4v, 
                           reverse = TRUE,
                           timewt = "n/G2")


#---leave PICNICS out----

data10y.5<-imp3.10y%>%
  filter(clus!="PICNICS")

data10y.5v<-imp3.10y%>%
  filter(clus=="PICNICS")

#Boundary knots location
data10y.5%>%
  filter(cens==1)%>%  #cens==1 event
  summarise(max(year),min(year))  

#refit model
model5.10<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl,data=data10y.5,k=1,bknots = c(log(0.5557837),log(9.596167)),scale = "odds")

h0.5.10<-predict(model5.10,newdata = data10y.5v,type="hazard",times=10)  #H0(t=10)
h.5.10<-predict(model5.10,newdata = data10y.5v,type="cumhaz",times=10)   #H(t=10)

lp.5.10<-log((exp(h.5.10[[2]])-1)/(exp(h0.5.10[[2]])-1))


#add linear predictor in validation datasets

data10y.5v$lp.5.10<-lp.5.10 

# Harrell's C
harrell_C_5v.10 <- concordance(Surv(year,cens) ~ lp.5.10, 
                              data10y.5v, 
                               reverse = TRUE)
# Uno's C
Uno_C_5v.10<- concordance(Surv(year,cens) ~ lp.5.10, 
                           data10y.5v, 
                           reverse = TRUE,
                           timewt = "n/G2")

#---leave PINE out----

data10y.6<-imp3.10y%>%
  filter(clus!="PINE")

data10y.6v<-imp3.10y%>%
  filter(clus=="PINE")

#Boundary knots location
data10y.6%>%
  filter(cens==1)%>%  #cens==1 event
  summarise(max(year),min(year))  

#refit model
model6.10<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl,data=data10y.6,k=1,bknots = c(log(0.1067762),log(9.943874)),scale = "odds")

h0.6.10<-predict(model6.10,newdata = data10y.6v,type="hazard",times=10)  #H0(t=10)
h.6.10<-predict(model6.10,newdata = data10y.6v,type="cumhaz",times=10)   #H(t=10)

lp.6.10<-log((exp(h.6.10[[2]])-1)/(exp(h0.6.10[[2]])-1))


#add linear predictor in validation datasets

data10y.6v$lp.6.10<-lp.6.10 

# Harrell's C
harrell_C_6v.10 <- concordance(Surv(year,cens) ~ lp.6.10, 
                              data10y.6v, 
                               reverse = TRUE)
# Uno's C
Uno_C_6v.10<- concordance(Surv(year,cens) ~ lp.6.10, 
                           data10y.6v, 
                           reverse = TRUE,
                           timewt = "n/G2")
```

```{r Time-dependent AUC 10 years}

#---leave CamPalGN out----

Uno_1v.10 <-
  timeROC::timeROC(
    T = data10y.1v$year, 
    delta = data10y.1v$cens,
    marker = data10y.1v$lp.1.10,
    cause = 1, 
    weighting = "marginal", 
    times = 9.99,
    iid = TRUE
  )

#---leave NYPUM out----

Uno_3v.10 <-
  timeROC::timeROC(
    T = data10y.3v$year, 
    delta = data10y.3v$cens,
    marker = data10y.3v$lp.3.10,
    cause = 1, 
    weighting = "marginal", 
    times = 9.99,
    iid = TRUE
  )


#---leave ParkWest out----

Uno_4v.10 <-
  timeROC::timeROC(
    T = data10y.4v$year, 
    delta = data10y.4v$cens,
    marker = data10y.4v$lp.4.10,
    cause = 1, 
    weighting = "marginal", 
    times = 6.99,
    iid = TRUE
  )


#ParkWest has less than 10 years

#---leave PICNICS out----

Uno_5v.10 <-
  timeROC::timeROC(
    T = data10y.5v$year, 
    delta = data10y.5v$cens,
    marker = data10y.5v$lp.5.10,
    cause = 1, 
    weighting = "marginal", 
    times = 9.99,
    iid = TRUE
  )

#---leave PINE out----

Uno_6v.10 <-
  timeROC::timeROC(
    T = data10y.6v$year, 
    delta = data10y.6v$cens,
    marker = data10y.6v$lp.6.10,
    cause = 1, 
    weighting = "marginal", 
    times = 9.99,
    iid = TRUE
  )

```


```{r Mean calibration 10 years}

# Observed / Expected ratio
alpha <- .05

#---leave CamPalGN out----

# Observed
obj.1.10 <- summary(survfit(
  Surv(year, cens) ~ 1, 
  data = data10y.1v),
  times = 10)

obs_t.1.10 <- 1 - obj.1.10$surv

data10y.1v$pred<-predict(model1.10,newdata = data10y.1v,type = "survival",times = 10)[[2]]  #survival probabilities

# Expected
exp_t.1.10 <-mean(1-data10y.1v$pred) #predicts risk, as 1 - S(t|X)


# Observed / Expected ratio
OE_t.1.10 <- obs_t.1.10 / exp_t.1.10

OE_summary.1.10 <- c(
  "OE" = OE_t.1.10,
  "2.5 %" = OE_t.1.10 * exp(-qnorm(1 - alpha / 2) * sqrt(1 / obj.1.10$n.event)),
  "97.5 %" = OE_t.1.10 * exp(+qnorm(1 - alpha / 2) * sqrt(1 / obj.1.10$n.event))
)

OE_summary.1.10


#---leave NYPUM out----

obj.3.10 <- summary(survfit(
  Surv(year, cens) ~ 1, 
  data = data10y.3v),
  times = 10)

obs_t.3.10 <- 1 - obj.3.10$surv

data10y.3v$pred<-predict(model3.10,newdata = data10y.3v,type = "survival",times = 10)[[2]]  #survival probabilities

# Expected
exp_t.3.10 <-mean(1-data10y.3v$pred) #predicts risk, as 1 - S(t|X)


# Observed / Expected ratio
OE_t.3.10 <- obs_t.3.10 / exp_t.3.10

OE_summary.3.10 <- c(
  "OE" = OE_t.3.10,
  "2.5 %" = OE_t.3.10 * exp(-qnorm(1 - alpha / 2) * sqrt(1 / obj.3.10$n.event)),
  "97.5 %" = OE_t.3.10 * exp(+qnorm(1 - alpha / 2) * sqrt(1 / obj.3.10$n.event))
)

OE_summary.3.10

#---leave ParkWest out----

obj.4.10 <- summary(survfit(
  Surv(year, cens) ~ 1, 
  data = data10y.4v),
  times = 7)

#ParkWest follow up time less than 10

obs_t.4.10 <- 1 - obj.4.10$surv

data10y.4v$pred<-predict(model4.10,newdata = data10y.4v,type = "survival",times = 10)[[2]]  #survival probabilities

# Expected
exp_t.4.10 <-mean(1-data10y.4v$pred) #predicts risk, as 1 - S(t|X)


# Observed / Expected ratio
OE_t.4.10 <- obs_t.4.10 / exp_t.4.10

OE_summary.4.10 <- c(
  "OE" = OE_t.4.10,
  "2.5 %" = OE_t.4.10 * exp(-qnorm(1 - alpha / 2) * sqrt(1 / obj.4.10$n.event)),
  "97.5 %" = OE_t.4.10 * exp(+qnorm(1 - alpha / 2) * sqrt(1 / obj.4.10$n.event))
)

OE_summary.4.10


#---leave PICNICS out----

obj.5.10 <- summary(survfit(
  Surv(year, cens) ~ 1, 
  data = data10y.5v),
  times = 10)

obs_t.5.10 <- 1 - obj.5.10$surv

data10y.5v$pred<-predict(model5.10,newdata = data10y.5v,type = "survival",times = 10)[[2]]  #survival probabilities

# Expected
exp_t.5.10 <-mean(1-data10y.5v$pred) #predicts risk, as 1 - S(t|X)


# Observed / Expected ratio
OE_t.5.10 <- obs_t.5.10 / exp_t.5.10

OE_summary.5.10 <- c(
  "OE" = OE_t.5.10,
  "2.5 %" = OE_t.5.10 * exp(-qnorm(1 - alpha / 2) * sqrt(1 / obj.5.10$n.event)),
  "97.5 %" = OE_t.5.10 * exp(+qnorm(1 - alpha / 2) * sqrt(1 / obj.5.10$n.event))
)

OE_summary.5.10

#---leave PINE out----

obj.6.10 <- summary(survfit(
  Surv(year, cens) ~ 1, 
  data = data10y.6v),
  times = 10)

obs_t.6.10 <- 1 - obj.6.10$surv

data10y.6v$pred<-predict(model6.10,newdata = data10y.6v,type = "survival",times = 10)[[2]]  #survival probabilities

# Expected
exp_t.6.10 <-mean(1-data10y.6v$pred) #predicts risk, as 1 - S(t|X)


# Observed / Expected ratio
OE_t.6.10 <- obs_t.6.10 / exp_t.6.10

OE_summary.6.10 <- c(
  "OE" = OE_t.6.10,
  "2.5 %" = OE_t.6.10 * exp(-qnorm(1 - alpha / 2) * sqrt(1 / obj.6.10$n.event)),
  "97.5 %" = OE_t.6.10 * exp(+qnorm(1 - alpha / 2) * sqrt(1 / obj.6.10$n.event))
)

OE_summary.6.10
```

```{r Weak calibration 10 years}

#Include linear predictor in validation datasets as a predictor

alpha<-0.05

#---leave CamPalGN out----

val.1.10 <- coxph(Surv(year, cens) ~ lp.1.10, data = data10y.1v)


  calslope_summary.1.10 <- c(
  "calibration slope" = val.1.10$coef,
  "2.5 %"  = val.1.10$coef - qnorm(1 - alpha / 2) * sqrt(val.1.10$var),
  "97.5 %" = val.1.10$coef + qnorm(1 - alpha / 2) * sqrt(val.1.10$var)
)

calslope_summary.1.10

#---leave NYPUM out----

val.3.10 <- coxph(Surv(year, cens) ~ lp.3.10, data = data10y.3v)

calslope_summary.3.10 <- c(
  "calibration slope" = val.3.10$coef,
  "2.5 %"  = val.3.10$coef - qnorm(1 - alpha / 2) * sqrt(val.3.10$var),
  "97.5 %" = val.3.10$coef + qnorm(1 - alpha / 2) * sqrt(val.3.10$var)
)

calslope_summary.3.10


#---leave ParkWest out----

val.4.10 <- coxph(Surv(year, cens) ~ lp.4.10, data = data10y.4v)

calslope_summary.4.10 <- c(
  "calibration slope" = val.4.10$coef,
  "2.5 %"  = val.4.10$coef - qnorm(1 - alpha / 2) * sqrt(val.4.10$var),
  "97.5 %" = val.4.10$coef + qnorm(1 - alpha / 2) * sqrt(val.4.10$var)
)

calslope_summary.4.10


#---leave PICNICS out----

val.5.10 <- coxph(Surv(year, cens) ~ lp.5.10, data = data10y.5v)

calslope_summary.5.10 <- c(
  "calibration slope" = val.5.10$coef,
  "2.5 %"  = val.5.10$coef - qnorm(1 - alpha / 2) * sqrt(val.5.10$var),
  "97.5 %" = val.5.10$coef + qnorm(1 - alpha / 2) * sqrt(val.5.10$var)
)

calslope_summary.5.10


#---leave PINE out----

val.6.10 <- coxph(Surv(year, cens) ~ lp.6.10, data = data10y.6v)

calslope_summary.6.10 <- c(
  "calibration slope" = val.6.10$coef,
  "2.5 %"  = val.6.10$coef - qnorm(1 - alpha / 2) * sqrt(val.6.10$var),
  "97.5 %" = val.6.10$coef + qnorm(1 - alpha / 2) * sqrt(val.6.10$var)
)

calslope_summary.6.10
```

```{r  Moderate calibration 10 years}

#moderate calibration uses smooth curves of predicted risk from a more complex ‘secondary’ Cox model against the predicted risk from the development model 


#---leave CamPalGN out----

# predicted risk

data10y.1v$pred<-predict(model1.10,newdata = data10y.1v,type = "survival",times = 10) #survival probabilities

data10y.1v$risk <-(1-data10y.1v$pred[[2]]) #predicted risk, as 1 - S(t|X),the probabilities of events

data10y.1v$risk.cll <- log(-log(1-data10y.1v$risk)) #complementary log-log link

# Estimate actual risk

vcal.1.10 <- cph(Surv(year, cens) ~ rcs(risk.cll, 3),
                 x = T,
                 y = T,
                 surv = T,
                 data = data10y.1v
) 

#survest function is to estimate survival probabilities

dat_cal.1.10 <- cbind.data.frame(
  "obs" = 1 - rms::survest(vcal.1.10,
                           times = 10,
                           newdata = data10y.1v)$surv, #1-s(t=5) to get the refitted model predicted risk
  
  "lower" = 1 - rms::survest(vcal.1.10,
                             times = 10,
                             newdata = data10y.1v)$upper,
  
  "upper" = 1 - rms::survest(vcal.1.10,
                             times = 10,
                             newdata = data10y.1v)$lower,
  "pred" = data10y.1v$risk
)


dat_cal.1.10 <- dat_cal.1.10[order(dat_cal.1.10$pred), ]

par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.1.10$pred, #x is predicted risk from the 
  y=dat_cal.1.10$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model",
  ylab = "Predicted risk from refitted model",  
  bty = "n" #no box
)

lines(dat_cal.1.10$pred, 
      dat_cal.1.10$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.1.10$pred, 
      dat_cal.1.10$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("bottomright",
        c("Ideal calibration",
          "Calibration curve based on secondary Cox model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.85)

# Numerical measures
absdiff_cph.1.10 <- abs(dat_cal.1.10$pred - dat_cal.1.10$obs)

numsum_cph.1.10 <- c(
  "ICI" = mean(absdiff_cph.1.10),
  setNames(quantile(absdiff_cph.1.10, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.1.10)
)
numsum_cph.1.10



#---leave NYPUM out----

# predicted risk

data10y.3v$pred<-predict(model3.10,newdata = data10y.3v,type = "survival",times = 10) #survival probabilities

data10y.3v$risk <-(1-data10y.3v$pred[[2]]) #predicted risk, as 1 - S(t|X),the probabilities of events

data10y.3v$risk.cll <- log(-log(1-data10y.3v$risk)) #complementary log-log link

# Estimate actual risk

vcal.3.10 <- cph(Surv(year, cens) ~ rcs(risk.cll, 3),
                 x = T,
                 y = T,
                 surv = T,
                 data = data10y.3v
) 

#survest function is to estimate survival probabilities

dat_cal.3.10 <- cbind.data.frame(
  "obs" = 1 - rms::survest(vcal.3.10,
                           times = 10,
                           newdata = data10y.3v)$surv, #1-s(t=5) to get the refitted model predicted risk
  
  "lower" = 1 - rms::survest(vcal.3.10,
                             times = 10,
                             newdata = data10y.3v)$upper,
  
  "upper" = 1 - rms::survest(vcal.3.10,
                             times = 10,
                             newdata = data10y.3v)$lower,
  "pred" = data10y.3v$risk
)


dat_cal.3.10 <- dat_cal.3.10[order(dat_cal.3.10$pred), ]

par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.3.10$pred, #x is predicted risk from the 
  y=dat_cal.3.10$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model",
  ylab = "Predicted risk from refitted model",  
  bty = "n" #no box
)

lines(dat_cal.3.10$pred, 
      dat_cal.3.10$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.3.10$pred, 
      dat_cal.3.10$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("bottomright",
        c("Ideal calibration",
          "Calibration curve based on secondary Cox model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.85)

# Numerical measures
absdiff_cph.3.10 <- abs(dat_cal.3.10$pred - dat_cal.3.10$obs)

numsum_cph.3.10 <- c(
  "ICI" = mean(absdiff_cph.3.10),
  setNames(quantile(absdiff_cph.3.10, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.3.10)
)
numsum_cph.3.10


#---leave ParkWest out----

# predicted risk


data10y.4v$pred<-predict(model4.10,newdata = data10y.4v,type = "survival",times = 10) #survival probabilities

data10y.4v$risk <-(1-data10y.4v$pred[[2]]) #predicted risk, as 1 - S(t|X),the probabilities of events

data10y.4v$risk.cll <- log(-log(1-data10y.4v$risk)) #complementary log-log link

# Estimate actual risk

vcal.4.10 <- cph(Surv(year, cens) ~ rcs(risk.cll, 3),
                 x = T,
                 y = T,
                 surv = T,
                 data = data10y.4v
) 

#survest function is to estimate survival probabilities

dat_cal.4.10 <- cbind.data.frame(
  "obs" = 1 - rms::survest(vcal.4.10,
                           times = 10,
                           newdata = data10y.4v)$surv, #1-s(t=5) to get the refitted model predicted risk
  
  "lower" = 1 - rms::survest(vcal.4.10,
                             times = 10,
                             newdata = data10y.4v)$upper,
  
  "upper" = 1 - rms::survest(vcal.4.10,
                             times = 10,
                             newdata = data10y.4v)$lower,
  "pred" = data10y.4v$risk
)


dat_cal.4.10 <- dat_cal.4.10[order(dat_cal.4.10$pred), ]

par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.4.10$pred, #x is predicted risk from the 
  y=dat_cal.4.10$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model",
  ylab = "Predicted risk from refitted model",  
  bty = "n" #no box
)

lines(dat_cal.4.10$pred, 
      dat_cal.4.10$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.4.10$pred, 
      dat_cal.4.10$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("bottomright",
        c("Ideal calibration",
          "Calibration curve based on secondary Cox model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.85)

# Numerical measures
absdiff_cph.4.10 <- abs(dat_cal.4.10$pred - dat_cal.4.10$obs)

numsum_cph.4.10 <- c(
  "ICI" = mean(absdiff_cph.4.10),
  setNames(quantile(absdiff_cph.4.10, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.4.10)
)
numsum_cph.4.10


#---leave PICNICS out----

data10y.5v$pred<-predict(model5.10,newdata = data10y.5v,type = "survival",times = 10) #survival probabilities

data10y.5v$risk <-(1-data10y.5v$pred[[2]]) #predicted risk, as 1 - S(t|X),the probabilities of events

data10y.5v$risk.cll <- log(-log(1-data10y.5v$risk)) #complementary log-log link

# Estimate actual risk

vcal.5.10 <- cph(Surv(year, cens) ~ rcs(risk.cll, 3),
                 x = T,
                 y = T,
                 surv = T,
                 data = data10y.5v
) 

#survest function is to estimate survival probabilities

dat_cal.5.10 <- cbind.data.frame(
  "obs" = 1 - rms::survest(vcal.5.10,
                           times = 10,
                           newdata = data10y.5v)$surv, #1-s(t=5) to get the refitted model predicted risk
  
  "lower" = 1 - rms::survest(vcal.5.10,
                             times = 10,
                             newdata = data10y.5v)$upper,
  
  "upper" = 1 - rms::survest(vcal.5.10,
                             times = 10,
                             newdata = data10y.5v)$lower,
  "pred" = data10y.5v$risk
)


dat_cal.5.10 <- dat_cal.5.10[order(dat_cal.5.10$pred), ]

par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.5.10$pred, #x is predicted risk from the 
  y=dat_cal.5.10$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model",
  ylab = "Predicted risk from refitted model",  
  bty = "n" #no box
)

lines(dat_cal.5.10$pred, 
      dat_cal.5.10$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.5.10$pred, 
      dat_cal.5.10$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("bottomright",
        c("Ideal calibration",
          "Calibration curve based on secondary Cox model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.85)

# Numerical measures
absdiff_cph.5.10 <- abs(dat_cal.5.10$pred - dat_cal.5.10$obs)

numsum_cph.5.10 <- c(
  "ICI" = mean(absdiff_cph.5.10),
  setNames(quantile(absdiff_cph.5.10, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.5.10)
)
numsum_cph.5.10

#---leave PINE out----

data10y.6v$pred<-predict(model6.10,newdata = data10y.6v,type = "survival",times = 10) #survival probabilities

data10y.6v$risk <-(1-data10y.6v$pred[[2]]) #predicted risk, as 1 - S(t|X),the probabilities of events

data10y.6v$risk.cll <- log(-log(1-data10y.6v$risk)) #complementary log-log link

# Estimate actual risk

vcal.6.10 <- cph(Surv(year, cens) ~ rcs(risk.cll, 3),
                 x = T,
                 y = T,
                 surv = T,
                 data = data10y.6v
) 

#survest function is to estimate survival probabilities

dat_cal.6.10 <- cbind.data.frame(
  "obs" = 1 - rms::survest(vcal.6.10,
                           times = 10,
                           newdata = data10y.6v)$surv, #1-s(t=5) to get the refitted model predicted risk
  
  "lower" = 1 - rms::survest(vcal.6.10,
                             times = 10,
                             newdata = data10y.6v)$upper,
  
  "upper" = 1 - rms::survest(vcal.6.10,
                             times = 10,
                             newdata = data10y.6v)$lower,
  "pred" = data10y.6v$risk
)


dat_cal.6.10 <- dat_cal.6.10[order(dat_cal.6.10$pred), ]

par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.6.10$pred, #x is predicted risk from the 
  y=dat_cal.6.10$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model",
  ylab = "Predicted risk from refitted model",  
  bty = "n" #no box
)

lines(dat_cal.6.10$pred, 
      dat_cal.6.10$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.6.10$pred, 
      dat_cal.6.10$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("bottomright",
        c("Ideal calibration",
          "Calibration curve based on secondary Cox model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.85)

# Numerical measures
absdiff_cph.6.10 <- abs(dat_cal.6.10$pred - dat_cal.6.10$obs)

numsum_cph.6.10 <- c(
  "ICI" = mean(absdiff_cph.6.10),
  setNames(quantile(absdiff_cph.6.10, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.6.10)
)
numsum_cph.6.10



```