---
title: "7 year without ICICLE"
output: html_document
date: '2022-10-13'
---
```{r library}
library(dplyr)
library(tidyr)
library(Hmisc)
library(jomo)
library(haven)
library(lubridate)
library(finalfit)
library(mice)
library(mitools)
library(rms)
library(mitml)
library(survminer)
library(patchwork) #Arrange plot
library(ggplot2)
library(GGally)
library(gridExtra)
library(kableExtra)
library(metafor)
library(png)
library(meta)
library(grid)
library(survival)
library(flexsurv)
library(pacman)
```



```{r 7 years model}

imp3.new <- read.csv("imp3.new.csv")


imp3.new10<-imp3.new%>%
  filter(clus!="ICICLE")

```

```{r censor for 7 years}

imp3.temp10<-survSplit(Surv(year, cens) ~ ., data = imp3.new10, cut = 7,
                  episode="timegroup")
imp3.10y<-subset(imp3.temp10, timegroup == 1) #only the first 7 year
```


```{r POPH compare 7 years}

imp3.10y%>%
  filter(cens==1)%>%  #cens==1 event
  summarise(max(year),min(year),median(year))

PO0.10<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal+clus,data=imp3.10y,k=0,scale = "odds") #log-logistic model

PO1.10<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal+clus,data=imp3.10y,k=1,bknots = c(log(0.1067762),log(6.976044)),scale = "odds")

PO2.10<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal+clus,data=imp3.10y,k=2,bknots = c(log(0.1067762),log(6.976044)),scale = "odds")

PH0.10<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal+clus,data=imp3.10y,k=0,scale = "hazard")

PH1.10<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal+clus,data=imp3.10y,k=1,bknots = c(log(0.1067762),log(6.976044)),scale = "hazard")

PH2.10<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal+clus,data=imp3.10y,k=2,bknots = c(log(0.1067762),log(6.976044)),scale = "hazard")

AIC(PO0.10) 
AIC(PO1.10) #1 knots in median
AIC(PO2.10) #2 knots one in 33% one in 67%

BIC(PO0.10) 
BIC(PO1.10) #1 knots in median
BIC(PO2.10) #2 knots one in 33% one in 67%


AIC(PH0.10) 
AIC(PH1.10) #1 knots in median
AIC(PH2.10) #2 knots one in 33% one in 67%

BIC(PH0.10) 
BIC(PH1.10) #1 knots in median
BIC(PH2.10) #2 knots one in 33% one in 67%

#same the final is PO1


```


```{r Harrell Uno 7 years}

#---leave CamPalGN out----

data10y.1<-imp3.10y%>%
  filter(clus!="CamPalGN")

data10y.1v<-imp3.10y%>%
  filter(clus=="CamPalGN")

#Boundary knots location
data10y.1%>%
  filter(cens==1)%>%  #cens==1 event
  summarise(max(year),min(year))  


#refit model
model1.10<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal,data=data10y.1,k=1,bknots = c(log(0.1067762),log(6.976044)),scale = "odds")


#linear predictor method 1
# Design matrix of predictors
des_matr1.10<-as.data.frame(model.matrix(~ age10+sex+mdsupdrs3.10+hybl+mmsebltotal,data=data10y.1v))
des_matr1.10$`(Intercept)` <- NULL
coef1.10<-c(model1.10$coefficients[4],model1.10$coefficients[5],model1.10$coefficients[6],model1.10$coefficients[7],model1.10$coefficients[8])
data10y.1v$lp.1.10 <- as.vector(as.matrix(des_matr1.10) %*% cbind(coef1.10))


# Harrell's C
harrell_C_1v.10 <- concordance(Surv(year,cens) ~ lp.1.10, 
                              data10y.1v, 
                               reverse = TRUE)
# Uno's C
Uno_C_1v.10<- concordance(Surv(year,cens) ~ lp.1.10, 
                           data10y.1v, 
                           reverse = TRUE,
                           timewt = "n/G2")

#---leave NYPUM out----

data10y.3<-imp3.10y%>%
  filter(clus!="NYPUM")

data10y.3v<-imp3.10y%>%
  filter(clus=="NYPUM")

#Boundary knots location
data10y.3%>%
  filter(cens==1)%>%  #cens==1 event
  summarise(max(year),min(year))  

#refit model
model3.10<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal,data=data10y.3,k=1,bknots = c(log(0.1067762),log(6.976044)),scale = "odds")

#linear predictor 
# Design matrix of predictors
des_matr3.10<-as.data.frame(model.matrix(~ age10+sex+mdsupdrs3.10+hybl+mmsebltotal,data=data10y.3v))
des_matr3.10$`(Intercept)` <- NULL
coef3.10<-c(model3.10$coefficients[4],model3.10$coefficients[5],model3.10$coefficients[6],model3.10$coefficients[7],model3.10$coefficients[8])
data10y.3v$lp.3.10 <- as.vector(as.matrix(des_matr3.10) %*% cbind(coef3.10))


# Harrell's C
harrell_C_3v.10 <- concordance(Surv(year,cens) ~ lp.3.10, 
                              data10y.3v, 
                               reverse = TRUE)
# Uno's C
Uno_C_3v.10<- concordance(Surv(year,cens) ~ lp.3.10, 
                           data10y.3v, 
                           reverse = TRUE,
                           timewt = "n/G2")


#---leave ParkWest out----

data10y.4<-imp3.10y%>%
  filter(clus!="ParkWest")

data10y.4v<-imp3.10y%>%
  filter(clus=="ParkWest")

#Boundary knots location
data10y.4%>%
  filter(cens==1)%>%  #cens==1 event
  summarise(max(year),min(year))  

#refit model
model4.10<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal,data=data10y.4,k=1,bknots = c(log(0.1067762),log(6.976044)),scale = "odds")

#linear predictor 
# Design matrix of predictors
des_matr4.10<-as.data.frame(model.matrix(~ age10+sex+mdsupdrs3.10+hybl+mmsebltotal,data=data10y.4v))
des_matr4.10$`(Intercept)` <- NULL
coef4.10<-c(model4.10$coefficients[4],model4.10$coefficients[5],model4.10$coefficients[6],model4.10$coefficients[7],model4.10$coefficients[8])
data10y.4v$lp.4.10 <- as.vector(as.matrix(des_matr4.10) %*% cbind(coef4.10))

# Harrell's C
harrell_C_4v.10 <- concordance(Surv(year,cens) ~ lp.4.10, 
                              data10y.4v, 
                               reverse = TRUE)
# Uno's C
Uno_C_4v.10<- concordance(Surv(year,cens) ~ lp.4.10, 
                           data10y.4v, 
                           reverse = TRUE,
                           timewt = "n/G2")


#---leave PICNICS out----

data10y.5<-imp3.10y%>%
  filter(clus!="PICNICS")

data10y.5v<-imp3.10y%>%
  filter(clus=="PICNICS")

#Boundary knots location
data10y.5%>%
  filter(cens==1)%>%  #cens==1 event
  summarise(max(year),min(year))  

#refit model
model5.10<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal,data=data10y.5,k=1,bknots = c(log(0.5557837),log(6.976044)),scale = "odds")

#linear predictor 
# Design matrix of predictors
des_matr5.10<-as.data.frame(model.matrix(~ age10+sex+mdsupdrs3.10+hybl+mmsebltotal,data=data10y.5v))
des_matr5.10$`(Intercept)` <- NULL
coef5.10<-c(model5.10$coefficients[4],model5.10$coefficients[5],model5.10$coefficients[6],model5.10$coefficients[7],model5.10$coefficients[8])
data10y.5v$lp.5.10 <- as.vector(as.matrix(des_matr5.10) %*% cbind(coef5.10))


# Harrell's C
harrell_C_5v.10 <- concordance(Surv(year,cens) ~ lp.5.10, 
                              data10y.5v, 
                               reverse = TRUE)
# Uno's C
Uno_C_5v.10<- concordance(Surv(year,cens) ~ lp.5.10, 
                           data10y.5v, 
                           reverse = TRUE,
                           timewt = "n/G2")

#---leave PINE out----

data10y.6<-imp3.10y%>%
  filter(clus!="PINE")

data10y.6v<-imp3.10y%>%
  filter(clus=="PINE")

#Boundary knots location
data10y.6%>%
  filter(cens==1)%>%  #cens==1 event
  summarise(max(year),min(year))  

#refit model
model6.10<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal,data=data10y.6,k=1,bknots = c(log(0.1067762),log(6.872005)),scale = "odds")

#linear predictor 
# Design matrix of predictors
des_matr6.10<-as.data.frame(model.matrix(~ age10+sex+mdsupdrs3.10+hybl+mmsebltotal,data=data10y.6v))
des_matr6.10$`(Intercept)` <- NULL
coef6.10<-c(model6.10$coefficients[4],model6.10$coefficients[5],model6.10$coefficients[6],model6.10$coefficients[7],model6.10$coefficients[8])
data10y.6v$lp.6.10 <- as.vector(as.matrix(des_matr6.10) %*% cbind(coef6.10))

# Harrell's C
harrell_C_6v.10 <- concordance(Surv(year,cens) ~ lp.6.10, 
                              data10y.6v, 
                               reverse = TRUE)
# Uno's C
Uno_C_6v.10<- concordance(Surv(year,cens) ~ lp.6.10, 
                           data10y.6v, 
                           reverse = TRUE,
                           timewt = "n/G2")
```

```{r Time-dependent AUC 7 years}

#---leave CamPalGN out----

Uno_1v.10 <-
  timeROC::timeROC(
    T = data10y.1v$year, 
    delta = data10y.1v$cens,
    marker = data10y.1v$lp.1.10,
    cause = 1, 
    weighting = "marginal", 
    times = 6.99,
    iid = TRUE
  )

#---leave NYPUM out----

Uno_3v.10 <-
  timeROC::timeROC(
    T = data10y.3v$year, 
    delta = data10y.3v$cens,
    marker = data10y.3v$lp.3.10,
    cause = 1, 
    weighting = "marginal", 
    times = 6.99,
    iid = TRUE
  )


#---leave ParkWest out----

Uno_4v.10 <-
  timeROC::timeROC(
    T = data10y.4v$year, 
    delta = data10y.4v$cens,
    marker = data10y.4v$lp.4.10,
    cause = 1, 
    weighting = "marginal", 
    times = 6.99,
    iid = TRUE
  )



#---leave PICNICS out----

Uno_5v.10 <-
  timeROC::timeROC(
    T = data10y.5v$year, 
    delta = data10y.5v$cens,
    marker = data10y.5v$lp.5.10,
    cause = 1, 
    weighting = "marginal", 
    times = 6.99,
    iid = TRUE
  )

#---leave PINE out----

Uno_6v.10 <-
  timeROC::timeROC(
    T = data10y.6v$year, 
    delta = data10y.6v$cens,
    marker = data10y.6v$lp.6.10,
    cause = 1, 
    weighting = "marginal", 
    times = 6.99,
    iid = TRUE
  )

```


```{r Discrimination 7 year}

harrell_C_1v.10 
harrell_C_3v.10 
harrell_C_4v.10 
harrell_C_5v.10
harrell_C_6v.10 


Uno_C_1v.10
Uno_C_3v.10
Uno_C_4v.10
Uno_C_5v.10
Uno_C_6v.10


Uno_1v.10
Uno_3v.10
Uno_4v.10
Uno_5v.10
Uno_6v.10
```

```{r Mean calibration 7 years}

# Observed / Expected ratio
alpha <- .05

#---leave CamPalGN out----

# Observed
obj.1.10 <- summary(survfit(
  Surv(year, cens) ~ 1, 
  data = data10y.1v),
  times = 7)

obs_t.1.10 <- 1 - obj.1.10$surv

data10y.1v$pred<-predict(model1.10,newdata = data10y.1v,type = "survival",times = 7)[[2]]  #survival probabilities

# Expected
exp_t.1.10 <-mean(1-data10y.1v$pred) #predicts risk, as 1 - S(t|X)


# Observed / Expected ratio
OE_t.1.10 <- obs_t.1.10 / exp_t.1.10

OE_summary.1.10 <- c(
  "OE" = OE_t.1.10,
  "2.5 %" = OE_t.1.10 * exp(-qnorm(1 - alpha / 2) * sqrt(1 / obj.1.10$n.event)),
  "97.5 %" = OE_t.1.10 * exp(+qnorm(1 - alpha / 2) * sqrt(1 / obj.1.10$n.event))
)

OE_summary.1.10


#---leave NYPUM out----

obj.3.10 <- summary(survfit(
  Surv(year, cens) ~ 1, 
  data = data10y.3v),
  times = 7)

obs_t.3.10 <- 1 - obj.3.10$surv

data10y.3v$pred<-predict(model3.10,newdata = data10y.3v,type = "survival",times = 7)[[2]]  #survival probabilities

# Expected
exp_t.3.10 <-mean(1-data10y.3v$pred) #predicts risk, as 1 - S(t|X)


# Observed / Expected ratio
OE_t.3.10 <- obs_t.3.10 / exp_t.3.10

OE_summary.3.10 <- c(
  "OE" = OE_t.3.10,
  "2.5 %" = OE_t.3.10 * exp(-qnorm(1 - alpha / 2) * sqrt(1 / obj.3.10$n.event)),
  "97.5 %" = OE_t.3.10 * exp(+qnorm(1 - alpha / 2) * sqrt(1 / obj.3.10$n.event))
)

OE_summary.3.10

#---leave ParkWest out----

obj.4.10 <- summary(survfit(
  Surv(year, cens) ~ 1, 
  data = data10y.4v),
  times = 7)

#ParkWest follow up time less than 10

obs_t.4.10 <- 1 - obj.4.10$surv

data10y.4v$pred<-predict(model4.10,newdata = data10y.4v,type = "survival",times = 7)[[2]]  #survival probabilities

# Expected
exp_t.4.10 <-mean(1-data10y.4v$pred) #predicts risk, as 1 - S(t|X)


# Observed / Expected ratio
OE_t.4.10 <- obs_t.4.10 / exp_t.4.10

OE_summary.4.10 <- c(
  "OE" = OE_t.4.10,
  "2.5 %" = OE_t.4.10 * exp(-qnorm(1 - alpha / 2) * sqrt(1 / obj.4.10$n.event)),
  "97.5 %" = OE_t.4.10 * exp(+qnorm(1 - alpha / 2) * sqrt(1 / obj.4.10$n.event))
)

OE_summary.4.10


#---leave PICNICS out----

obj.5.10 <- summary(survfit(
  Surv(year, cens) ~ 1, 
  data = data10y.5v),
  times = 7)

obs_t.5.10 <- 1 - obj.5.10$surv

data10y.5v$pred<-predict(model5.10,newdata = data10y.5v,type = "survival",times = 7)[[2]]  #survival probabilities

# Expected
exp_t.5.10 <-mean(1-data10y.5v$pred) #predicts risk, as 1 - S(t|X)


# Observed / Expected ratio
OE_t.5.10 <- obs_t.5.10 / exp_t.5.10

OE_summary.5.10 <- c(
  "OE" = OE_t.5.10,
  "2.5 %" = OE_t.5.10 * exp(-qnorm(1 - alpha / 2) * sqrt(1 / obj.5.10$n.event)),
  "97.5 %" = OE_t.5.10 * exp(+qnorm(1 - alpha / 2) * sqrt(1 / obj.5.10$n.event))
)

OE_summary.5.10

#---leave PINE out----

obj.6.10 <- summary(survfit(
  Surv(year, cens) ~ 1, 
  data = data10y.6v),
  times = 7)

obs_t.6.10 <- 1 - obj.6.10$surv

data10y.6v$pred<-predict(model6.10,newdata = data10y.6v,type = "survival",times = 7)[[2]]  #survival probabilities

# Expected
exp_t.6.10 <-mean(1-data10y.6v$pred) #predicts risk, as 1 - S(t|X)


# Observed / Expected ratio
OE_t.6.10 <- obs_t.6.10 / exp_t.6.10

OE_summary.6.10 <- c(
  "OE" = OE_t.6.10,
  "2.5 %" = OE_t.6.10 * exp(-qnorm(1 - alpha / 2) * sqrt(1 / obj.6.10$n.event)),
  "97.5 %" = OE_t.6.10 * exp(+qnorm(1 - alpha / 2) * sqrt(1 / obj.6.10$n.event))
)

OE_summary.6.10
```


```{r  Moderate calibration 7 years not run in CamPalGN}

#moderate calibration uses smooth curves of predicted risk from a more complex ‘secondary’ Cox model against the predicted risk from the development model 


#---leave CamPalGN out----

#data10y.1v$pred<-predict(model1.10,newdata = data10y.1v,type = "survival",times = 7)[[2]]  #survival probabilities

# predicted risk

data10y.1v$risk <-(1-data10y.1v$pred) #predicted risk, as 1 - S(t|X),the probabilities of events

data10y.1v$risk.cll <- log(-log(1-data10y.1v$risk)) #complementary log-log link

#Check location of knots again

data10y.1v%>%
  filter(cens==1)%>%  #cens==1 event
  summarise(max(year),min(year))  


# Estimate actual risk

vcal.1.10.RP <- flexsurvspline(Surv(year, cens) ~rcs(risk.cll,3), data = data10y.1v, k=1,bknots = c(log(1.147159),log(6.773443)),scale = "odds")

#Error in optim(method = "BFGS", par = c(gamma0 = 1248.46031146024, gamma1 = 9.60937995841959e-10,  : initial value in 'vmmin' is not finite

#survest function is to estimate survival probabilities

dat_cal.1.10 <- cbind.data.frame(
  "obs" = 1 - predict(vcal.1.10.RP,
                      type = "survival",
                      times = 7,
                      newdata = data10y.1v)[[2]], #1-s(t=4) to get the refitted model predicted risk
  
  "lower" = 1 - predict(vcal.1.10.RP,
                      type = "survival",
                      conf.int = T,
                      times = 7,
                      newdata = data10y.1v)[[4]],
  
  "upper" = 1 - predict(vcal.1.10.RP,
                      type = "survival",
                      conf.int = T,
                      times = 7,
                      newdata = data10y.1v)[[3]],
  "pred" = data10y.1v$risk
)


dat_cal.1.10 <- dat_cal.1.10[order(dat_cal.1.10$pred), ]

#png("Cam-7y.png",width = 3500,height =2000,res = 400)
par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.1.10$pred, #x is predicted risk from the 
  y=dat_cal.1.10$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model",
  ylab = "Predicted risk from refitted model",  
  main = "Validation dataset is CamPalGN",
  bty = "n" #no box
)

lines(dat_cal.1.10$pred, 
      dat_cal.1.10$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.1.10$pred, 
      dat_cal.1.10$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend(0.07,0.9,
        c("Ideal calibration",
          "Calibration curve based on secondary Royston-Parmar model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.8)
#dev.off()

# Numerical measures
absdiff_cph.1.10 <- abs(dat_cal.1.10$pred - dat_cal.1.10$obs)

numsum_cph.1.10 <- c(
  "ICI" = mean(absdiff_cph.1.10),
  setNames(quantile(absdiff_cph.1.10, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.1.10)
)
numsum_cph.1.10



#---leave NYPUM out----

# predicted risk

data10y.3v$risk <-(1-data10y.3v$pred) #predicted risk, as 1 - S(t|X),the probabilities of events

data10y.3v$risk.cll <- log(-log(1-data10y.3v$risk)) #complementary log-log link

#Check location of knots again

data10y.3v%>%
  filter(cens==1)%>%  #cens==1 event
  summarise(max(year),min(year))  


flexsurvspline(Surv(year, cens) ~ risk.cll, data = data10y.3v,scale = "odds")

# Estimate actual risk

vcal.3.10.RP <- flexsurvspline(Surv(year, cens) ~ rcs(risk.cll,3), data = data10y.3v, k=1,bknots = c(log(0.8925394),log(6.735113)),scale = "odds")


dat_cal.3.10 <- cbind.data.frame(
  "obs" = 1 - predict(vcal.3.10.RP,
                      type = "survival",
                      times = 7,
                      newdata = data10y.3v)[[2]], #1-s(t=4) to get the refitted model predicted risk
  
  "lower" = 1 - predict(vcal.3.10.RP,
                      type = "survival",
                      conf.int = T,
                      times = 7,
                      newdata = data10y.3v)[[4]],
  
  "upper" = 1 - predict(vcal.3.10.RP,
                      type = "survival",
                      conf.int = T,
                      times = 7,
                      newdata = data10y.3v)[[3]],
  "pred" = data10y.3v$risk
)


dat_cal.3.10 <- dat_cal.3.10[order(dat_cal.3.10$pred), ]

png("NY-7y(new).png",width = 3500,height =3500,res = 400)
par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.3.10$pred, #x is predicted risk from the 
  y=dat_cal.3.10$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model",
  ylab = "Predicted risk from refitted model", 
  main = "Validation dataset is NYPUM",
  bty = "n" #no box
)

lines(dat_cal.3.10$pred, 
      dat_cal.3.10$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.3.10$pred, 
      dat_cal.3.10$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("topleft",
        c("Ideal calibration",
          "Calibration curve based on secondary Royston-Parmar model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.8)
dev.off()

# Numerical measures
absdiff_cph.3.10 <- abs(dat_cal.3.10$pred - dat_cal.3.10$obs)

numsum_cph.3.10 <- c(
  "ICI" = mean(absdiff_cph.3.10),
  setNames(quantile(absdiff_cph.3.10, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.3.10)
)
numsum_cph.3.10


#---leave ParkWest out----

# predicted risk

data10y.4v$risk <-(1-data10y.4v$pred) #predicted risk, as 1 - S(t|X),the probabilities of events

data10y.4v$risk.cll <- log(-log(1-data10y.4v$risk)) #complementary log-log link

#Check location of knots again

data10y.4v%>%
  filter(cens==1)%>%  #cens==1 event
  summarise(max(year),min(year))  


# Estimate actual risk

vcal.4.10.RP <- flexsurvspline(Surv(year, cens) ~ rcs(risk.cll,3), data = data10y.4v, k=1,bknots = c(log(1.990418),log(6.729637)),scale = "odds")

dat_cal.4.10 <- cbind.data.frame(
  "obs" = 1 - predict(vcal.4.10.RP,
                      type = "survival",
                      times = 7,
                      newdata = data10y.4v)[[2]], #1-s(t=4) to get the refitted model predicted risk
  
  "lower" = 1 - predict(vcal.4.10.RP,
                      type = "survival",
                      conf.int = T,
                      times = 7,
                      newdata = data10y.4v)[[4]],
  
  "upper" = 1 - predict(vcal.4.10.RP,
                      type = "survival",
                      conf.int = T,
                      times = 7,
                      newdata = data10y.4v)[[3]],
  "pred" = data10y.4v$risk
)


dat_cal.4.10 <- dat_cal.4.10[order(dat_cal.4.10$pred), ]

png("PA-7y.png",width = 3500,height =3500,res = 400)
par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.4.10$pred, #x is predicted risk from the 
  y=dat_cal.4.10$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model",
  ylab = "Predicted risk from refitted model",  
  main = "Validation dataset is ParkWest",
  bty = "n" #no box
)

lines(dat_cal.4.10$pred, 
      dat_cal.4.10$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.4.10$pred, 
      dat_cal.4.10$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("topleft",
        c("Ideal calibration",
          "Calibration curve based on secondary Royston-Parmar model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.7)
dev.off()

# Numerical measures
absdiff_cph.4.10 <- abs(dat_cal.4.10$pred - dat_cal.4.10$obs)

numsum_cph.4.10 <- c(
  "ICI" = mean(absdiff_cph.4.10),
  setNames(quantile(absdiff_cph.4.10, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.4.10)
)
numsum_cph.4.10


#---leave PICNICS out----

data10y.5v$risk <-(1-data10y.5v$pred) #predicted risk, as 1 - S(t|X),the probabilities of events

data10y.5v$risk.cll <- log(-log(1-data10y.5v$risk)) #complementary log-log link

#Check location of knots again

data10y.5v%>%
  filter(cens==1)%>%  #cens==1 event
  summarise(max(year),min(year))  


# Estimate actual risk

vcal.5.10.RP <- flexsurvspline(Surv(year, cens) ~ rcs(risk.cll,3), data = data10y.5v, k=1,bknots = c(log(0.1067762),log(6.872005)),scale = "odds")


dat_cal.5.10 <- cbind.data.frame(
  "obs" = 1 - predict(vcal.5.10.RP,
                      type = "survival",
                      times = 7,
                      newdata = data10y.5v)[[2]], #1-s(t=4) to get the refitted model predicted risk
  
  "lower" = 1 - predict(vcal.5.10.RP,
                      type = "survival",
                      conf.int = T,
                      times = 7,
                      newdata = data10y.5v)[[4]],
  
  "upper" = 1 - predict(vcal.5.10.RP,
                      type = "survival",
                      conf.int = T,
                      times = 7,
                      newdata = data10y.5v)[[3]],
  "pred" = data10y.5v$risk
)


dat_cal.5.10 <- dat_cal.5.10[order(dat_cal.5.10$pred), ]

png("PIC-7y.png",width = 3500,height =3500,res = 400)
par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.5.10$pred, #x is predicted risk from the 
  y=dat_cal.5.10$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model",
  ylab = "Predicted risk from refitted model",  
  main = "Validation dataset is PICNICS",
  bty = "n" #no box
)

lines(dat_cal.5.10$pred, 
      dat_cal.5.10$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.5.10$pred, 
      dat_cal.5.10$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("topleft",
        c("Ideal calibration",
          "Calibration curve based on secondary Royston-Parmar model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.8)
dev.off()

# Numerical measures
absdiff_cph.5.10 <- abs(dat_cal.5.10$pred - dat_cal.5.10$obs)

numsum_cph.5.10 <- c(
  "ICI" = mean(absdiff_cph.5.10),
  setNames(quantile(absdiff_cph.5.10, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.5.10)
)
numsum_cph.5.10

#---leave PINE out----

data10y.6v$risk <-(1-data10y.6v$pred) #predicted risk, as 1 - S(t|X),the probabilities of events

data10y.6v$risk.cll <- log(-log(1-data10y.6v$risk)) #complementary log-log link

#Check location of knots again

data10y.6v%>%
  filter(cens==1)%>%  #cens==1 event
  summarise(max(year),min(year))  


# Estimate actual risk

vcal.6.10.RP <- flexsurvspline(Surv(year, cens) ~ rcs(risk.cll,3), data = data10y.6v, k=1,bknots = c(log(0.5557837),log(6.976044)),scale = "odds")


dat_cal.6.10 <- cbind.data.frame(
  "obs" = 1 - predict(vcal.6.10.RP,
                      type = "survival",
                      times = 7,
                      newdata = data10y.6v)[[2]], #1-s(t=4) to get the refitted model predicted risk
  
  "lower" = 1 - predict(vcal.6.10.RP,
                      type = "survival",
                      conf.int = T,
                      times = 7,
                      newdata = data10y.6v)[[4]],
  
  "upper" = 1 - predict(vcal.6.10.RP,
                      type = "survival",
                      conf.int = T,
                      times = 7,
                      newdata = data10y.6v)[[3]],
  "pred" = data10y.6v$risk
)


dat_cal.6.10 <- dat_cal.6.10[order(dat_cal.6.10$pred), ]

png("PIN-7y.png",width = 3500,height =3500,res = 400)
par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.6.10$pred, #x is predicted risk from the 
  y=dat_cal.6.10$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model",
  ylab = "Predicted risk from refitted model",  
  main = "Validation dataset is PINE",
  bty = "n" #no box
)

lines(dat_cal.6.10$pred, 
      dat_cal.6.10$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.6.10$pred, 
      dat_cal.6.10$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("topleft",
        c("Ideal calibration",
          "Calibration curve based on secondary Royston-Parmar model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.8)
dev.off()

# Numerical measures
absdiff_cph.6.10 <- abs(dat_cal.6.10$pred - dat_cal.6.10$obs)

numsum_cph.6.10 <- c(
  "ICI" = mean(absdiff_cph.6.10),
  setNames(quantile(absdiff_cph.6.10, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.6.10)
)
numsum_cph.6.10

```


```{r Weak calibration 7 years}

#take the linear predictor from the original RP model then fit a RP model with this linear predictor as the only covariate

#---leave CamPalGN out----

vcal.1.10.weak <- flexsurvspline(Surv(year, cens) ~lp.1.10, data = data10y.1v, k=1,bknots = c(log(1.147159),log(6.773443)),scale = "odds")

vcal.1.10.weak$res[c("lp.1.10"), c("est","L95%","U95%")] #weak calibration value 


#---leave NYPUM out----

vcal.3.10.weak <- flexsurvspline(Surv(year, cens) ~lp.3.10, data = data10y.3v, k=1,bknots = c(log(0.8925394), log(6.735113)),scale = "odds")

vcal.3.10.weak$res[c("lp.3.10"), c("est","L95%","U95%")] #weak calibration value 

#---leave ParkWest out----

vcal.4.10.weak <- flexsurvspline(Surv(year, cens) ~lp.4.10, data = data10y.4v, k=1,bknots = c(log(1.990418), log(6.729637)),scale = "odds")

vcal.4.10.weak$res[c("lp.4.10"), c("est","L95%","U95%")] #weak calibration value 


#---leave PICNICS out----

vcal.5.10.weak <- flexsurvspline(Surv(year, cens) ~lp.5.10, data = data10y.5v, k=1,bknots = c(log(0.1067762), log(6.872005)),scale = "odds")

vcal.5.10.weak$res[c("lp.5.10"), c("est","L95%","U95%")] #weak calibration value 


#---leave PINE out----

vcal.6.10.weak <- flexsurvspline(Surv(year, cens) ~lp.6.10, data = data10y.6v, k=1,bknots = c(log(0.5557837), log(6.976044)),scale = "odds")

vcal.6.10.weak$res[c("lp.6.10"), c("est","L95%","U95%")] #weak calibration value 

```



```{r  recalibration in large year7 not CamPalGN}

#----NYPUM-----


#vcal.3.10.weak <- flexsurvspline(Surv(year, cens) ~lp.3.10, data = data10y.1v, k=1,bknots = c(log(0.8925394), log(6.735113),scale = "odds")

init.pars.3.10<-vcal.3.10.weak$res.t[,"est"]

#fitting a model with only one free parameter, and with an offset variable equal to the linear predictor of the original model

init.pars.3.10["lp.3.10"]<-1  #offset variable is the linear predictor and fixed the coefficient is one

recal.large.3.10<-flexsurvspline(Surv(year, cens) ~lp.3.10, data = data10y.3v, k=1,
                                 bknots = c(log(0.8925394), log(6.735113)),scale = "odds",
                                 inits=init.pars.3.10,
                                 fixedpars=which(names(init.pars.3.10)=="lp.3.10")) #fixed slope =1

recal.large.3.10$res[c("gamma0", "gamma1", "gamma2"), "est"]

# The models were updated by adding the coefficient of the free parameter to the linear predictor

data10y.3v$pred.re<-1/(1+exp(-12.1282004+1.9951417*data10y.3v$rcs1-0.6618196*data10y.3v$rcs2+data10y.3v$lp.3.10)) #change the knots position and s(lnt;r) but keep the linear predictor the same

(1-obj.3.10$surv)/mean(1-data10y.3v$pred.re) #Mean calibration improve
#Before is (1-obj.3.10$surv)/mean(1-data10y.3v$pred), 1.292101, now is 0.9034988

data10y.3v$risk.re<-1-data10y.3v$pred.re

dat_cal.3.10.RP.re <- cbind.data.frame(
  "obs" = 1 - predict(vcal.3.10.RP,
                      type = "survival",
                      times = 7,
                      newdata = data10y.3v)[[2]], #1-s(t=4) to get the refitted model predicted risk
  
  "lower" = 1 - predict(vcal.3.10.RP,
                        type = "survival",
                        conf.int = T,
                        times = 7,
                        newdata = data10y.3v)[[4]],
  
  "upper" = 1 - predict(vcal.3.10.RP,
                        type = "survival",
                        conf.int = T,
                        times = 7,
                        newdata = data10y.3v)[[3]],
  "pred" = data10y.3v$risk.re
)


dat_cal.3.10.RP.re <- dat_cal.3.10.RP.re[order(dat_cal.3.10.RP.re$pred), ]


png("NY-7y-re1.png",width = 3500,height =3500,res = 400)
par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.3.10.RP.re$pred, #x is predicted risk from the 
  y=dat_cal.3.10.RP.re$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model with new boundary knots position and intercept",
  ylab = "Predicted risk from refitted model",  
  main = "Validation dataset is NYPUM",
  bty = "n" #no box
)

lines(dat_cal.3.10.RP.re$pred, 
      dat_cal.3.10.RP.re$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.3.10.RP.re$pred, 
      dat_cal.3.10.RP.re$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("topleft",
        c("Ideal calibration",
          "Calibration curve based on secondary Royston-Parmar model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.8)
dev.off()

# Numerical measures
absdiff_cph.3.10.RP.re <- abs(dat_cal.3.10.RP.re$pred - dat_cal.3.10.RP.re$obs)

numsum_cph.3.10.RP.re <- c(
  "ICI" = mean(absdiff_cph.3.10.RP.re),
  setNames(quantile(absdiff_cph.3.10.RP.re, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.3.10.RP.re)
)
numsum_cph.3.10.RP.re


#----ParkWest-----


#vcal.4.10.weak <- flexsurvspline(Surv(year, cens) ~lp.4.10, data = data10y.4v, k=1,bknots = c(log(1.990418), log(6.729637)),scale = "odds")

init.pars.4.10<-vcal.4.10.weak$res.t[,"est"]

init.pars.4.10["lp.4.10"]<-1

recal.large.4.10<-flexsurvspline(Surv(year, cens) ~lp.4.10, data = data10y.4v, k=1,
                                 bknots = c(log(1.990418), log(6.729637)),scale = "odds",
                                 inits=init.pars.4.10,
                                 fixedpars=which(names(init.pars.4.10)=="lp.4.10")) #fixed slope =1

recal.large.4.10$res[c("gamma0", "gamma1", "gamma2"), "est"]

data10y.4v$pred.re<-1/(1+exp(-15.027157+4.468972*data10y.4v$rcs1+1.606316*data10y.4v$rcs2+data10y.4v$lp.4.10)) #change the knots position and s(lnt;r) but keep the linear predictor the same


(1-obj.4.10$surv)/mean(1-data10y.4v$pred.re) #Mean calibration improve
#Before is (1-obj.4.10$surv)/mean(1-data10y.4v$pred), 0.85, now is 1.03


data10y.4v$risk.re<-1-data10y.4v$pred.re

dat_cal.4.10.RP.re <- cbind.data.frame(
  "obs" = 1 - predict(vcal.4.10.RP,
                      type = "survival",
                      times = 7,
                      newdata = data10y.4v)[[2]], #1-s(t=4) to get the refitted model predicted risk
  
  "lower" = 1 - predict(vcal.4.10.RP,
                        type = "survival",
                        conf.int = T,
                        times = 7,
                        newdata = data10y.4v)[[4]],
  
  "upper" = 1 - predict(vcal.4.10.RP,
                        type = "survival",
                        conf.int = T,
                        times = 7,
                        newdata = data10y.4v)[[3]],
  "pred" = data10y.4v$risk.re
)


dat_cal.4.10.RP.re <- dat_cal.4.10.RP.re[order(dat_cal.4.10.RP.re$pred), ]

png("PA-7y-re1(new).png",width = 3500,height =3500,res = 400)
par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.4.10.RP.re$pred, #x is predicted risk from the 
  y=dat_cal.4.10.RP.re$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model with new boundary knots position and intercept",
  ylab = "Predicted risk from refitted model",  
  main ="Validation dataset is ParkWest",
  bty = "n" #no box
)

lines(dat_cal.4.10.RP.re$pred, 
      dat_cal.4.10.RP.re$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.4.10.RP.re$pred, 
      dat_cal.4.10.RP.re$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("topleft",
        c("Ideal calibration",
          "Calibration curve based on secondary Royston-Parmar model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.8)
dev.off()

# Numerical measures
absdiff_cph.4.10.RP.re <- abs(dat_cal.4.10.RP.re$pred - dat_cal.4.10.RP.re$obs)

numsum_cph.4.10.RP.re <- c(
  "ICI" = mean(absdiff_cph.4.10.RP.re),
  setNames(quantile(absdiff_cph.4.10.RP.re, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.4.10.RP.re)
)
numsum_cph.4.10.RP.re


#----PICNICS----


#vcal.5.10.weak<-flexsurvspline(formula = Surv(year, cens) ~ lp.5.10, data = data10y.5v, k = 1, bknots = c(log(0.1067762), log(6.872005)), scale = "odds")

init.pars.5.10<-vcal.5.10.weak$res.t[,"est"]

init.pars.5.10["lp.5.10"]<-1

recal.large.5.10<-flexsurvspline(Surv(year, cens) ~lp.5.10, data = data10y.5v, k=1,
                                 bknots = c(log(0.1067762), log(6.872005)),scale = "odds",
                                 inits=init.pars.5.10,
                                 fixedpars=which(names(init.pars.5.10)=="lp.5.10")) #fixed slope =1


recal.large.5.10$res[c("gamma0", "gamma1", "gamma2"), "est"]

data10y.5v$pred.re<-1/(1+exp(-12.8382157+0.6028209*data10y.5v$rcs1-0.5012445*data10y.5v$rcs2+data10y.5v$lp.5.10)) #change the knots position and s(lnt;r) but keep the linear predictor the same

(1-obj.5.10$surv)/mean(1-data10y.5v$pred.re) #Mean calibration improve
#Before is 0.67, now is 0.74

data10y.5v$risk.re<-1-data10y.5v$pred.re

dat_cal.5.10.RP.re <- cbind.data.frame(
  "obs" = 1 - predict(vcal.5.10.RP,
                      type = "survival",
                      times = 7,
                      newdata = data10y.5v)[[2]], #1-s(t=4) to get the refitted model predicted risk
  
  "lower" = 1 - predict(vcal.5.10.RP,
                        type = "survival",
                        conf.int = T,
                        times = 7,
                        newdata = data10y.5v)[[4]],
  
  "upper" = 1 - predict(vcal.5.10.RP,
                        type = "survival",
                        conf.int = T,
                        times = 7,
                        newdata = data10y.5v)[[3]],
  "pred" = data10y.5v$risk.re
)


dat_cal.5.10.RP.re <- dat_cal.5.10.RP.re[order(dat_cal.5.10.RP.re$pred), ]

png("PIC-7y-re1.png",width = 3500,height =3500,res = 400)
par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.5.10.RP.re$pred, #x is predicted risk from the 
  y=dat_cal.5.10.RP.re$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model with new boundary knots position and intercept",
  ylab = "Predicted risk from refitted model",  
  main = "Validation dataset is PICNICS",
  bty = "n" #no box
)

lines(dat_cal.5.10.RP.re$pred, 
      dat_cal.5.10.RP.re$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.5.10.RP.re$pred, 
      dat_cal.5.10.RP.re$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("topleft",
        c("Ideal calibration",
          "Calibration curve based on secondary Royston-Parmar model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.8)
dev.off()

# Numerical measures
absdiff_cph.5.10.RP.re <- abs(dat_cal.5.10.RP.re$pred - dat_cal.5.10.RP.re$obs)

numsum_cph.5.10.RP.re <- c(
  "ICI" = mean(absdiff_cph.5.10.RP.re),
  setNames(quantile(absdiff_cph.5.10.RP.re, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.5.10.RP.re)
)
numsum_cph.5.10.RP.re


#----PINE----



#vcal.6.10.weak<-flexsurvspline(formula = Surv(year, cens) ~ lp.6.10, data = data10y.6v, k = 1, bknots = c(log(0.5557837), log(6.976044)), scale = "odds")



init.pars.6.10<-vcal.6.10.weak$res.t[,"est"]

init.pars.6.10["lp.6.10"]<-1

recal.large.6.10<-flexsurvspline(Surv(year, cens) ~lp.6.10, data = data10y.6v, k=1,
                                 bknots = c(log(0.5557837), log(6.976044)),scale = "odds",
                                 inits=init.pars.6.10,
                                 fixedpars=which(names(init.pars.6.10)=="lp.6.10")) #fixed slope =1


recal.large.6.10$res[c("gamma0", "gamma1", "gamma2"), "est"]


data10y.6v$pred.re<-1/(1+exp(-16.3122292+1.6498915*data10y.6v$rcs1-0.2744948*data10y.6v$rcs2+data10y.6v$lp.6.10)) #change the knots position and s(lnt;r) but keep the linear predictor the same

(1-obj.6.10$surv)/mean(1-data10y.6v$pred.re) #Mean calibration improve
#Before is 0.95, now is 1.01

data10y.6v$risk.re<-1-data10y.6v$pred.re

dat_cal.6.10.RP.re <- cbind.data.frame(
  "obs" = 1 - predict(vcal.6.10.RP,
                      type = "survival",
                      times = 7,
                      newdata = data10y.6v)[[2]], #1-s(t=4) to get the refitted model predicted risk
  
  "lower" = 1 - predict(vcal.6.10.RP,
                        type = "survival",
                        conf.int = T,
                        times = 7,
                        newdata = data10y.6v)[[4]],
  
  "upper" = 1 - predict(vcal.6.10.RP,
                        type = "survival",
                        conf.int = T,
                        times = 7,
                        newdata = data10y.6v)[[3]],
  "pred" = data10y.6v$risk.re
)


dat_cal.6.10.RP.re <- dat_cal.6.10.RP.re[order(dat_cal.6.10.RP.re$pred), ]

png("PIA-7y-re1.png",width = 3500,height =3500,res = 400)
par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.6.10.RP.re$pred, #x is predicted risk from the 
  y=dat_cal.6.10.RP.re$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model with new boundary knots position and intercept",
  ylab = "Predicted risk from refitted model",  
  main = "Validation dataset is PINE",
  bty = "n" #no box
)

lines(dat_cal.6.10.RP.re$pred, 
      dat_cal.6.10.RP.re$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.6.10.RP.re$pred, 
      dat_cal.6.10.RP.re$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("topleft",
        c("Ideal calibration",
          "Calibration curve based on secondary Royston-Parmar model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.8)
dev.off()

# Numerical measures
absdiff_cph.6.10.RP.re <- abs(dat_cal.6.10.RP.re$pred - dat_cal.6.10.RP.re$obs)

numsum_cph.6.10.RP.re <- c(
  "ICI" = mean(absdiff_cph.6.10.RP.re),
  setNames(quantile(absdiff_cph.6.10.RP.re, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.6.10.RP.re)
)
numsum_cph.6.10.RP.re

```



```{r recalibration2 times slope}

#-----NYPUM----

#by fitting a model with the linear predictor of the original model as a single predictor. The models were then updated by multiplying the linear predictor by the coefficient and adding the estimated intercept; the individual risks were then recalculated


#vcal.3.10.weak <- flexsurvspline(Surv(year, cens) ~lp.3.10, data = data10y.3v, k=1,bknots = c(log(0.8925394), log(6.735113)),scale = "odds")


vcal.3.10.weak$res[c("gamma0", "gamma1", "gamma2","lp.3.10"), "est"]


data10y.3v$pred.re.1<-1/(1+exp(-14.3152188
                               +2.0753194*data10y.3v$rcs1-0.7844244*data10y.3v$rcs2+1.2735178*data10y.3v$lp.3.10)) 




(1-obj.3.10$surv)/mean(1-data10y.3v$pred.re.1) #Mean calibration improve
#Before is (1-obj.3.10$surv)/mean(1-data10y.3v$pred.re) from 0.902 to 0.903

data10y.3v$risk.re.1<-1-data10y.3v$pred.re.1

dat_cal.3.10.RP.re.1 <- cbind.data.frame(
  "obs" = 1 - predict(vcal.3.10.RP,
                      type = "survival",
                      times = 7,
                      newdata = data10y.3v)[[2]], #1-s(t=4) to get the refitted model predicted risk
  
  "lower" = 1 - predict(vcal.3.10.RP,
                        type = "survival",
                        conf.int = T,
                        times = 7,
                        newdata = data10y.3v)[[4]],
  
  "upper" = 1 - predict(vcal.3.10.RP,
                        type = "survival",
                        conf.int = T,
                        times = 7,
                        newdata = data10y.3v)[[3]],
  "pred" = data10y.3v$risk.re.1
)


dat_cal.3.10.RP.re.1 <- dat_cal.3.10.RP.re.1[order(dat_cal.3.10.RP.re.1$pred), ]

png("NY-7y-re2.png",width = 3500,height =3500,res = 400)
par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.3.10.RP.re.1$pred, #x is predicted risk from the 
  y=dat_cal.3.10.RP.re.1$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model with new boundary knots position and intercept and coefficients",
  ylab = "Predicted risk from refitted model",  
  main = "Validation dataset is NYPUM",
  bty = "n" #no box
)

lines(dat_cal.3.10.RP.re.1$pred, 
      dat_cal.3.10.RP.re.1$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.3.10.RP.re.1$pred, 
      dat_cal.3.10.RP.re.1$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("topleft",
        c("Ideal calibration",
          "Calibration curve based on secondary Royston-Parmar model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.8)
dev.off()

# Numerical measures
absdiff_cph.3.10.RP.re.1 <- abs(dat_cal.3.10.RP.re.1$pred - dat_cal.3.10.RP.re.1$obs)

numsum_cph.3.10.RP.re.1 <- c(
  "ICI" = mean(absdiff_cph.3.10.RP.re.1),
  setNames(quantile(absdiff_cph.3.10.RP.re.1, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.3.10.RP.re.1)
)
numsum_cph.3.10.RP.re.1


#-----ParkWest----


#vcal.4.10.weak

vcal.4.10.weak$res[c("gamma0", "gamma1", "gamma2","lp.4.10"), "est"]

data10y.4v$pred.re.1<-1/(1+exp(-14.2067387+4.4101074*data10y.4v$rcs1+1.6273690*data10y.4v$rcs2+0.8775062*data10y.4v$lp.4.10)) #change the knots position and s(lnt;r) but keep the linear predictor the same


(1-obj.4.10$surv)/mean(1-data10y.4v$pred.re.1) #Mean calibration decrease
#Before is (1-obj.4.10$surv)/mean(1-data10y.4v$pred.re), 1.03, now is 1.05 



data10y.4v$risk.re.1<-1-data10y.4v$pred.re.1

dat_cal.4.10.RP.re.1 <- cbind.data.frame(
  "obs" = 1 - predict(vcal.4.10.RP,
                      type = "survival",
                      times = 7,
                      newdata = data10y.4v)[[2]], #1-s(t=4) to get the refitted model predicted risk
  
  "lower" = 1 - predict(vcal.4.10.RP,
                        type = "survival",
                        conf.int = T,
                        times = 7,
                        newdata = data10y.4v)[[4]],
  
  "upper" = 1 - predict(vcal.4.10.RP,
                        type = "survival",
                        conf.int = T,
                        times = 7,
                        newdata = data10y.4v)[[3]],
  "pred" = data10y.4v$risk.re.1
)


dat_cal.4.10.RP.re.1 <- dat_cal.4.10.RP.re.1[order(dat_cal.4.10.RP.re.1$pred), ]


png("PA-7y-re2(new).png",width = 3500,height =3500,res = 400)
par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.4.10.RP.re.1$pred, #x is predicted risk from the 
  y=dat_cal.4.10.RP.re.1$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model with new boundary knots position and intercept and coefficients",
  ylab = "Predicted risk from refitted model",  
  main = "Validation dataset is ParkWest",
  bty = "n" #no box
)

lines(dat_cal.4.10.RP.re.1$pred, 
      dat_cal.4.10.RP.re.1$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.4.10.RP.re.1$pred, 
      dat_cal.4.10.RP.re.1$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("topleft",
        c("Ideal calibration",
          "Calibration curve based on secondary Royston-Parmar model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.8)
dev.off()

# Numerical measures
absdiff_cph.4.10.RP.re.1 <- abs(dat_cal.4.10.RP.re.1$pred - dat_cal.4.10.RP.re.1$obs)

numsum_cph.4.10.RP.re.1 <- c(
  "ICI" = mean(absdiff_cph.4.10.RP.re.1),
  setNames(quantile(absdiff_cph.4.10.RP.re.1, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.4.10.RP.re.1)
)
numsum_cph.4.10.RP.re.1


#----PICNICS----


#vcal.5.10.weak

vcal.5.10.weak$res[c("gamma0", "gamma1", "gamma2","lp.5.10"), "est"]


data10y.5v$pred.re.1<-1/(1+exp(-13.9887831+0.6034252*data10y.5v$rcs1-0.5216810 *data10y.5v$rcs2+1.1456284*data10y.5v$lp.5.10)) 

(1-obj.5.10$surv)/mean(1-data10y.5v$pred.re.1) #Mean calibration decrease
#Before is (1-obj.5.10$surv)/mean(1-data10y.5v$pred.re) 0.75, now is 0.75

data10y.5v$risk.re.1<-1-data10y.5v$pred.re.1

dat_cal.5.10.RP.re.1 <- cbind.data.frame(
  "obs" = 1 - predict(vcal.5.10.RP,
                      type = "survival",
                      times = 7,
                      newdata = data10y.5v)[[2]], #1-s(t=4) to get the refitted model predicted risk
  
  "lower" = 1 - predict(vcal.5.10.RP,
                        type = "survival",
                        conf.int = T,
                        times = 7,
                        newdata = data10y.5v)[[4]],
  
  "upper" = 1 - predict(vcal.5.10.RP,
                        type = "survival",
                        conf.int = T,
                        times = 7,
                        newdata = data10y.5v)[[3]],
  "pred" = data10y.5v$risk.re.1
)


dat_cal.5.10.RP.re.1 <- dat_cal.5.10.RP.re.1[order(dat_cal.5.10.RP.re.1$pred), ]


png("PIC-7y-re2.png",width = 3500,height =3500,res = 400)
par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.5.10.RP.re.1$pred, #x is predicted risk from the 
  y=dat_cal.5.10.RP.re.1$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model with new boundary knots position and intercept and coefficients",
  ylab = "Predicted risk from refitted model",  
  main = "Validation dataset is PICNICS",
  bty = "n" #no box
)

lines(dat_cal.5.10.RP.re.1$pred, 
      dat_cal.5.10.RP.re.1$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.5.10.RP.re.1$pred, 
      dat_cal.5.10.RP.re.1$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("topleft",
        c("Ideal calibration",
          "Calibration curve based on secondary Royston-Parmar model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.8)
dev.off()

# Numerical measures
absdiff_cph.5.10.RP.re.1 <- abs(dat_cal.5.10.RP.re.1$pred - dat_cal.5.10.RP.re.1$obs)

numsum_cph.5.10.RP.re.1 <- c(
  "ICI" = mean(absdiff_cph.5.10.RP.re.1),
  setNames(quantile(absdiff_cph.5.10.RP.re.1, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.5.10.RP.re.1)
)
numsum_cph.5.10.RP.re.1

#----PINE-----

#vcal.6.10.weak

vcal.6.10.weak$res[c("gamma0", "gamma1", "gamma2","lp.6.10"), "est"]



data10y.6v$pred.re.1<-1/(1+exp(-10.8379543+1.6024924*data10y.6v$rcs1-0.1754959*data10y.6v$rcs2+0.5607001*data10y.6v$lp.6.10))

(1-obj.6.10$surv)/mean(1-data10y.6v$pred.re.1) #Mean calibration decrease
#Before is (1-obj.6.10$surv)/mean(1-data10y.6v$pred.re) 1.01,now 1.01

data10y.6v$risk.re.1<-1-data10y.6v$pred.re.1

dat_cal.6.10.RP.re.1 <- cbind.data.frame(
  "obs" = 1 - predict(vcal.6.10.RP,
                      type = "survival",
                      times = 7,
                      newdata = data10y.6v)[[2]], #1-s(t=4) to get the refitted model predicted risk
  
  "lower" = 1 - predict(vcal.6.10.RP,
                        type = "survival",
                        conf.int = T,
                        times = 7,
                        newdata = data10y.6v)[[4]],
  
  "upper" = 1 - predict(vcal.6.10.RP,
                        type = "survival",
                        conf.int = T,
                        times = 7,
                        newdata = data10y.6v)[[3]],
  "pred" = data10y.6v$risk.re.1
)


dat_cal.6.10.RP.re.1 <- dat_cal.6.10.RP.re.1[order(dat_cal.6.10.RP.re.1$pred), ]

png("PIN-7y-re2.png",width = 3500,height =3500,res = 400)
par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.6.10.RP.re.1$pred, #x is predicted risk from the 
  y=dat_cal.6.10.RP.re.1$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model with new boundary knots position and intercept and coefficients",
  ylab = "Predicted risk from refitted model",  
  main = "Validation dataset is PINE",
  bty = "n" #no box
)

lines(dat_cal.6.10.RP.re.1$pred, 
      dat_cal.6.10.RP.re.1$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.6.10.RP.re.1$pred, 
      dat_cal.6.10.RP.re.1$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("topleft",
        c("Ideal calibration",
          "Calibration curve based on secondary Royston-Parmar model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.8)
dev.off()

# Numerical measures
absdiff_cph.6.10.RP.re.1 <- abs(dat_cal.6.10.RP.re.1$pred - dat_cal.6.10.RP.re.1$obs)

numsum_cph.6.10.RP.re.1 <- c(
  "ICI" = mean(absdiff_cph.6.10.RP.re.1),
  setNames(quantile(absdiff_cph.6.10.RP.re.1, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.6.10.RP.re.1)
)
numsum_cph.6.10.RP.re.1

```


```{r mean calibration after recalibration}

#-----NYPUM----

OE_t.3.10.re <- (1-obj.3.10$surv)/mean(1-data10y.3v$pred.re)

OE_summary.3.10.re <- c(
  "OE" = OE_t.3.10.re,
  "2.5 %" = OE_t.3.10.re * exp(-qnorm(1 - alpha / 2) * sqrt(1 / obj.3.10$n.event)),
  "97.5 %" = OE_t.3.10.re * exp(+qnorm(1 - alpha / 2) * sqrt(1 / obj.3.10$n.event))
)

OE_summary.3.10.re


OE_t.3.10.re.1 <- (1-obj.3.10$surv)/mean(1-data10y.3v$pred.re.1)

OE_summary.3.10.re.1 <- c(
  "OE" = OE_t.3.10.re.1,
  "2.5 %" = OE_t.3.10.re.1 * exp(-qnorm(1 - alpha / 2) * sqrt(1 / obj.3.10$n.event)),
  "97.5 %" = OE_t.3.10.re.1 * exp(+qnorm(1 - alpha / 2) * sqrt(1 / obj.3.10$n.event))
)

OE_summary.3.10.re.1




#-----ParKwest----

OE_t.4.10.re <- (1-obj.4.10$surv)/mean(1-data10y.4v$pred.re)

OE_summary.4.10.re <- c(
  "OE" = OE_t.4.10.re,
  "2.5 %" = OE_t.4.10.re * exp(-qnorm(1 - alpha / 2) * sqrt(1 / obj.4.10$n.event)),
  "97.5 %" = OE_t.4.10.re * exp(+qnorm(1 - alpha / 2) * sqrt(1 / obj.4.10$n.event))
)

OE_summary.4.10.re


OE_t.4.10.re.1 <- (1-obj.4.10$surv)/mean(1-data10y.4v$pred.re.1)

OE_summary.4.10.re.1 <- c(
  "OE" = OE_t.4.10.re.1,
  "2.5 %" = OE_t.4.10.re.1 * exp(-qnorm(1 - alpha / 2) * sqrt(1 / obj.4.10$n.event)),
  "97.5 %" = OE_t.4.10.re.1 * exp(+qnorm(1 - alpha / 2) * sqrt(1 / obj.4.10$n.event))
)

OE_summary.4.10.re.1



#----PICNICS----

OE_t.5.10.re <- (1-obj.5.10$surv)/mean(1-data10y.5v$pred.re)

OE_summary.5.10.re <- c(
  "OE" = OE_t.5.10.re,
  "2.5 %" = OE_t.5.10.re * exp(-qnorm(1 - alpha / 2) * sqrt(1 / obj.5.10$n.event)),
  "97.5 %" = OE_t.5.10.re * exp(+qnorm(1 - alpha / 2) * sqrt(1 / obj.5.10$n.event))
)

OE_summary.5.10.re

OE_t.5.10.re.1 <- (1-obj.5.10$surv)/mean(1-data10y.5v$pred.re.1)

OE_summary.5.10.re.1 <- c(
  "OE" = OE_t.5.10.re.1,
  "2.5 %" = OE_t.5.10.re.1 * exp(-qnorm(1 - alpha / 2) * sqrt(1 / obj.5.10$n.event)),
  "97.5 %" = OE_t.5.10.re.1 * exp(+qnorm(1 - alpha / 2) * sqrt(1 / obj.5.10$n.event))
)

OE_summary.5.10.re.1



#----PINE----

OE_t.6.10.re <- (1-obj.6.10$surv)/mean(1-data10y.6v$pred.re)

OE_summary.6.10.re <- c(
  "OE" = OE_t.6.10.re,
  "2.5 %" = OE_t.6.10.re * exp(-qnorm(1 - alpha / 2) * sqrt(1 / obj.6.10$n.event)),
  "97.5 %" = OE_t.6.10.re * exp(+qnorm(1 - alpha / 2) * sqrt(1 / obj.6.10$n.event))
)

OE_summary.6.10.re

OE_t.6.10.re.1 <- (1-obj.6.10$surv)/mean(1-data10y.6v$pred.re.1)

OE_summary.6.10.re.1 <- c(
  "OE" = OE_t.6.10.re.1,
  "2.5 %" = OE_t.6.10.re.1 * exp(-qnorm(1 - alpha / 2) * sqrt(1 / obj.6.10$n.event)),
  "97.5 %" = OE_t.6.10.re.1 * exp(+qnorm(1 - alpha / 2) * sqrt(1 / obj.6.10$n.event))
)

OE_summary.6.10.re.1


```

```{r get the final recalibration model}

#---original CamPalGN----

round(model1.10$res[c("age10","sex","mdsupdrs3.10","hybl","mmsebltotal"),c("est","L95%","U95%")],2)

model1.10



#---NYPUM update intercept and coefficients---

round(1.27*model3.10$res[c("age10","sex","mdsupdrs3.10","hybl","mmsebltotal"),c("est","L95%","U95%")],2)

#---ParkWest only update intercept----

data10y.4v$pred.re<-1/(1+exp(-15.027157+4.468972*data10y.4v$rcs1+1.606316*data10y.4v$rcs2+data10y.4v$lp.4.10)) 

round(model4.10$res[c("age10","sex","mdsupdrs3.10","hybl","mmsebltotal"),c("est","L95%","U95%")],2)

#---PICNICS only update intercept----

data10y.5v$pred.re<-1/(1+exp(-12.8382157+0.6028209*data10y.5v$rcs1-0.5012445*data10y.5v$rcs2+data10y.5v$lp.5.10)) #change the knots position and s(lnt;r) but keep the linear predictor the same

round(model5.10$res[c("age10","sex","mdsupdrs3.10","hybl","mmsebltotal"),c("est","L95%","U95%")],2)


#---PINE update intercept and coefficients----

data10y.6v$pred.re.1<-1/(1+exp(-10.8379543+1.6024924*data10y.6v$rcs1-0.1754959*data10y.6v$rcs2+0.5607001*data10y.6v$lp.6.10))

round(0.56*model6.10$res[c("age10","sex","mdsupdrs3.10","hybl","mmsebltotal"),c("est","L95%","U95%")],2)

-0.005190967*0.56

```


```{r Check outlier in model 7 year}
imp3.10y%>%
  group_by(clus)%>%
  summarise(sum(cens))
 #PINE has much more events than others

ggplot(imp3.10y, aes(x=clus, y=agebl, fill=clus)) + 
    geom_boxplot()

imp3.10y%>%
  filter(cens==1)%>%
  group_by(clus)%>%
  summarise(min(agebl),max(agebl),mean(agebl)) #PINE has one patient very young but even after remove it didn't improve,which means more impact the model than just outliers.


ggplot(imp3.10y[imp3.10y$cens==1,], aes(x=clus, y=agebl, fill=clus)) + 
    geom_boxplot()


imp3.10y%>%
  group_by(clus)%>%
  summarise(min(agebl),max(agebl),mean(agebl),median(agebl)) #Look at the min and max age in groups, actually not that much difference.
```

```{r KM plot 7}
agegroup1.7<-imp3.10y%>%
  filter(agebl<60)

agegroup2.7<-imp3.10y%>%
  filter(agebl>=60 & agebl<80)

agegroup3.7<-imp3.10y%>%
  filter(agebl>=80)

KM1.7<-survfit(Surv(year,cens)~clus,data=agegroup1.7)
ggsurvplot(KM1.7,
           ylab="Cumulative probability of institutionalisation",
           xlab="Time to institutionalisation",
           legend="top",
           surv.median.line = "hv",
           fun="event",
           risk.table = F,
           ggtheme = theme_bw(),
           legend.labs=c("CamPalGN","NYPUM","ParkWest","PICNICS","PINE"))


KM2.7<-survfit(Surv(year,cens)~clus,data=agegroup2.7)
ggsurvplot(KM2.7,
           ylab="Cumulative probability of institutionalisation",
           xlab="Time to institutionalisation",
           legend="top",
           surv.median.line = "hv",
           fun="event",
           risk.table = F,
           ggtheme = theme_bw(),
           legend.labs=c("CamPalGN","NYPUM","ParkWest","PICNICS","PINE"))


KM3.7<-survfit(Surv(year,cens)~clus,data=agegroup3.7)
ggsurvplot(KM3.7,
           ylab="Cumulative probability of institutionalisation",
           xlab="Time to institutionalisation",
           legend="top",
           surv.median.line = "hv",
           fun="event",
           risk.table = F,
           ggtheme = theme_bw(),
           legend.labs=c("CamPalGN","NYPUM","ParkWest","PICNICS","PINE"))

```


```{r try no run}



rp.tmp <- flexsurvspline(
  Surv(year, cens) ~ lp.3.10,
  data = data10y.3v,
  k = 1,
  bknots = c(log(0.8925394), log(6.735113)),
  scale = "odds"
)

# Extract all estimated parameters
init.pars <- rp.tmp$res.t[, "est"]

# Find which one corresponds to lp.3.10
names(init.pars)

init.pars["lp.3.10"] <- 1


rp.recal.large <- flexsurvspline(
  Surv(year, cens) ~ lp.3.10,
  data = data10y.3v,
  k = 1,
  bknots = c(log(0.8925394), log(6.735113)),
  scale = "odds",
  inits = init.pars,
  fixedpars = which(names(init.pars) == "lp.3.10")  # fixes slope=1
)





rp.recal.large$res[c("gamma0", "gamma1", "gamma2"), "est"]

data10y.3v$pred.re<-1/(1+exp(-12.128+1.995*data10y.3v$rcs1-0.662*data10y.3v$rcs2+data10y.3v$lp.3.10)) #change the knots position and s(lnt;r) but keep the linear predictor the same


model3.10.re$res[c("gamma0", "gamma1", "gamma2"), "est"]

data10y.3v$pred.re<-1/(1+exp(-12.0726537+1.5879919*data10y.3v$rcs1-0.6935843*data10y.3v$rcs2+data10y.3v$lp.3.10)) #change the knots position and s(lnt;r) but keep the linear predictor the same

(1-obj.3.10$surv)/mean(1-data10y.3v$pred.re) #Mean calibration improve
#Before is (1-obj.3.10$surv)/mean(1-data10y.3v$pred), 1.292101, now is 1.090322


data10y.3v$risk.re<-1-data10y.3v$pred.re

dat_cal.3.10.RP.re <- cbind.data.frame(
  "obs" = 1 - predict(vcal.3.10.RP,
                      type = "survival",
                      times = 7,
                      newdata = data10y.3v)[[2]], #1-s(t=4) to get the refitted model predicted risk
  
  "lower" = 1 - predict(vcal.3.10.RP,
                        type = "survival",
                        conf.int = T,
                        times = 7,
                        newdata = data10y.3v)[[4]],
  
  "upper" = 1 - predict(vcal.3.10.RP,
                        type = "survival",
                        conf.int = T,
                        times = 7,
                        newdata = data10y.3v)[[3]],
  "pred" = data10y.3v$risk.re
)


dat_cal.3.10.RP.re <- dat_cal.3.10.RP.re[order(dat_cal.3.10.RP.re$pred), ]


png("NY-7y-nouse.png",width = 3500,height =3500,res = 400)
par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.3.10.RP.re$pred, #x is predicted risk from the 
  y=dat_cal.3.10.RP.re$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model with new boundary knots position and intercept",
  ylab = "Predicted risk from refitted model",  
  main = "Validation dataset is NYPUM",
  bty = "n" #no box
)

lines(dat_cal.3.10.RP.re$pred, 
      dat_cal.3.10.RP.re$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.3.10.RP.re$pred, 
      dat_cal.3.10.RP.re$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("topleft",
        c("Ideal calibration",
          "Calibration curve based on secondary Royston-Parmar model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.8)
dev.off()


```

```{r not run 2}

vcal.3.10.weak <- flexsurvspline(Surv(year, cens) ~lp.3.10, data = data10y.3v, k=1,bknots = c(log(0.8925394), log(6.735113)),scale = "odds")

vcal.3.10.weak $res[c("gamma0", "gamma1", "gamma2"), "est"]

data10y.3v$pred.re.1<-1/(1+exp(-14.315 
                               + 2.075*data10y.3v$rcs1-0.784*data10y.3v$rcs2+1.274*data10y.3v$lp.3.10)) #change the knots position and s(lnt;r) but keep the linear predictor the same


#It should be -10.22739 (weak calibration intercept) - (-12.0726537+0.2490932 (log mean calraibtion) +1.5879919*data10y.3v$rcs1-0.6935843*data10y.3v$rcs2 (the same part from recalibration based on mean calibration))
                         
#-7.598721=-12.0726537+0.2490932+1.5879919*data10y.3v$rcs1-0.6935843*data10y.3v$rcs2

#-10.22739+7.598721



(1-obj.3.10$surv)/mean(1-data10y.3v$pred.re.1) #Mean calibration improve
#Before is (1-obj.3.10$surv)/mean(1-data10y.3v$pred.re) from 1.09 to 0.94

data10y.3v$risk.re.1<-1-data10y.3v$pred.re.1

dat_cal.3.10.RP.re.1 <- cbind.data.frame(
  "obs" = 1 - predict(vcal.3.10.RP,
                      type = "survival",
                      times = 7,
                      newdata = data10y.3v)[[2]], #1-s(t=4) to get the refitted model predicted risk
  
  "lower" = 1 - predict(vcal.3.10.RP,
                        type = "survival",
                        conf.int = T,
                        times = 7,
                        newdata = data10y.3v)[[4]],
  
  "upper" = 1 - predict(vcal.3.10.RP,
                        type = "survival",
                        conf.int = T,
                        times = 7,
                        newdata = data10y.3v)[[3]],
  "pred" = data10y.3v$risk.re.1
)


dat_cal.3.10.RP.re.1 <- dat_cal.3.10.RP.re.1[order(dat_cal.3.10.RP.re.1$pred), ]

png("NY-7y-re2_nouse.png",width = 3500,height =3500,res = 400)
par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.3.10.RP.re.1$pred, #x is predicted risk from the 
  y=dat_cal.3.10.RP.re.1$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model with new boundary knots position and intercept and coefficients",
  ylab = "Predicted risk from refitted model",  
  main = "Validation dataset is NYPUM",
  bty = "n" #no box
)

lines(dat_cal.3.10.RP.re.1$pred, 
      dat_cal.3.10.RP.re.1$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.3.10.RP.re.1$pred, 
      dat_cal.3.10.RP.re.1$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("topleft",
        c("Ideal calibration",
          "Calibration curve based on secondary Royston-Parmar model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.8)
dev.off()

```