---
title: "10 YEARS?"
author: "Yan Li"
date: '2022-11-02'
output: html_document
---

```{r censor for 10 years}
imp3.new12<-imp3.new%>%
  filter(clus=="CamPalGN" |clus=="NYPUM"|clus=="PICNICS"|clus=="PINE" )

imp3.temp12<-survSplit(Surv(year, cens) ~ ., data = imp3.new12, cut = 10,
                  episode="timegroup")
imp3.12y<-subset(imp3.temp12, timegroup == 1) #only the first 10 year
```


```{r exclude ICICLE ParkWest}

imp3.12y%>%
  filter(cens==1)%>%  #cens==1 event
  summarise(max(year),min(year),median(year))
  
PO0.12<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal+clus,data=imp3.new12,k=0,scale = "odds") #log-logistic model

PO1.12<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal+clus,data=imp3.new12,k=1,bknots = c(log(0.1067762),log(9.943874)),scale = "odds")

PO2.12<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal+clus,data=imp3.new12,k=2,bknots = c(log(0.1067762),log(9.943874)),scale = "odds")

PH0.12<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal+clus,data=imp3.new12,k=0,scale = "hazard")

PH1.12<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal+clus,data=imp3.new12,k=1,bknots = c(log(0.1067762),log(9.943874)),scale = "hazard")

PH2.12<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal+clus,data=imp3.new12,k=2,bknots = c(log(0.1067762),log(9.943874)),scale = "hazard")

```

```{r POPH compare 10 years}

AIC(PO0.12) 
AIC(PO1.12) #1 knots in median
AIC(PO2.12) #2 knots one in 33% one in 67%

BIC(PO0.12) 
BIC(PO1.12) #1 knots in median
BIC(PO2.12) #2 knots one in 33% one in 67%


AIC(PH0.12) 
AIC(PH1.12) #1 knots in median
AIC(PH2.12) #2 knots one in 33% one in 67%

BIC(PH0.12) 
BIC(PH1.12) #1 knots in median
BIC(PH2.12) #2 knots one in 33% one in 67%

#same the final is PO1

PO1.12
```


```{r Harrell Uno 7 years}

#---leave CamPalGN out----

data12y.1<-imp3.12y%>%
  filter(clus!="CamPalGN")

data12y.1v<-imp3.12y%>%
  filter(clus=="CamPalGN")

#Boundary knots location
data12y.1%>%
  filter(cens==1)%>%  #cens==1 event
  summarise(max(year),min(year))  


#refit model
model1.12<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal,data=data12y.1,k=1,bknots = c(log(0.1067762),log(9.943874)),scale = "odds")


#linear predictor method 1
# Design matrix of predictors
des_matr1.12<-as.data.frame(model.matrix(~ age10+sex+mdsupdrs3.10+hybl+mmsebltotal,data=data12y.1v))
des_matr1.12$`(Intercept)` <- NULL
coef1.12<-c(model1.12$coefficients[4],model1.12$coefficients[5],model1.12$coefficients[6],model1.12$coefficients[7],model1.12$coefficients[8])
data12y.1v$lp.1.12 <- as.vector(as.matrix(des_matr1.12) %*% cbind(coef1.12))


# Harrell's C
harrell_C_1v.12 <- concordance(Surv(year,cens) ~ lp.1.12, 
                              data12y.1v, 
                               reverse = TRUE)
# Uno's C
Uno_C_1v.12<- concordance(Surv(year,cens) ~ lp.1.12, 
                           data12y.1v, 
                           reverse = TRUE,
                           timewt = "n/G2")

#---leave NYPUM out----

data12y.3<-imp3.12y%>%
  filter(clus!="NYPUM")

data12y.3v<-imp3.12y%>%
  filter(clus=="NYPUM")

#Boundary knots location
data12y.3%>%
  filter(cens==1)%>%  #cens==1 event
  summarise(max(year),min(year))  

#refit model
model3.12<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal,data=data12y.3,k=1,bknots = c(log(0.1067762),log(9.943874)),scale = "odds")

#linear predictor 
# Design matrix of predictors
des_matr3.12<-as.data.frame(model.matrix(~ age10+sex+mdsupdrs3.10+hybl+mmsebltotal,data=data12y.3v))
des_matr3.12$`(Intercept)` <- NULL
coef3.12<-c(model3.12$coefficients[4],model3.12$coefficients[5],model3.12$coefficients[6],model3.12$coefficients[7],model3.12$coefficients[8])
data12y.3v$lp.3.12 <- as.vector(as.matrix(des_matr3.12) %*% cbind(coef3.12))


# Harrell's C
harrell_C_3v.12 <- concordance(Surv(year,cens) ~ lp.3.12, 
                              data12y.3v, 
                               reverse = TRUE)
# Uno's C
Uno_C_3v.12<- concordance(Surv(year,cens) ~ lp.3.12, 
                           data12y.3v, 
                           reverse = TRUE,
                           timewt = "n/G2")


#---leave PICNICS out----

data12y.5<-imp3.12y%>%
  filter(clus!="PICNICS")

data12y.5v<-imp3.12y%>%
  filter(clus=="PICNICS")

#Boundary knots location
data12y.5%>%
  filter(cens==1)%>%  #cens==1 event
  summarise(max(year),min(year))  

#refit model
model5.12<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal,data=data12y.5,k=1,bknots = c(log(0.5557837),log(9.596167)),scale = "odds")

#linear predictor 
# Design matrix of predictors
des_matr5.12<-as.data.frame(model.matrix(~ age10+sex+mdsupdrs3.10+hybl+mmsebltotal,data=data12y.5v))
des_matr5.12$`(Intercept)` <- NULL
coef5.12<-c(model5.12$coefficients[4],model5.12$coefficients[5],model5.12$coefficients[6],model5.12$coefficients[7],model5.12$coefficients[8])
data12y.5v$lp.5.12 <- as.vector(as.matrix(des_matr5.12) %*% cbind(coef5.12))


# Harrell's C
harrell_C_5v.12 <- concordance(Surv(year,cens) ~ lp.5.12, 
                              data12y.5v, 
                               reverse = TRUE)
# Uno's C
Uno_C_5v.12<- concordance(Surv(year,cens) ~ lp.5.12, 
                           data12y.5v, 
                           reverse = TRUE,
                           timewt = "n/G2")

#---leave PINE out----

data12y.6<-imp3.12y%>%
  filter(clus!="PINE")

data12y.6v<-imp3.12y%>%
  filter(clus=="PINE")

#Boundary knots location
data12y.6%>%
  filter(cens==1)%>%  #cens==1 event
  summarise(max(year),min(year))  

#refit model
model6.12<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal,data=data12y.6,k=1,bknots = c(log(0.1067762),log(9.943874)),scale = "odds")

#linear predictor 
# Design matrix of predictors
des_matr6.12<-as.data.frame(model.matrix(~ age10+sex+mdsupdrs3.10+hybl+mmsebltotal,data=data12y.6v))
des_matr6.12$`(Intercept)` <- NULL
coef6.12<-c(model6.12$coefficients[4],model6.12$coefficients[5],model6.12$coefficients[6],model6.12$coefficients[7],model6.12$coefficients[8])
data12y.6v$lp.6.12 <- as.vector(as.matrix(des_matr6.12) %*% cbind(coef6.12))

# Harrell's C
harrell_C_6v.12 <- concordance(Surv(year,cens) ~ lp.6.12, 
                              data12y.6v, 
                               reverse = TRUE)
# Uno's C
Uno_C_6v.12<- concordance(Surv(year,cens) ~ lp.6.12, 
                           data12y.6v, 
                           reverse = TRUE,
                           timewt = "n/G2")
```

```{r Time-dependent AUC 10 years}

#---leave CamPalGN out----

Uno_1v.12 <-
  timeROC::timeROC(
    T = data12y.1v$year, 
    delta = data12y.1v$cens,
    marker = data12y.1v$lp.1.12,
    cause = 1, 
    weighting = "marginal", 
    times = 9.99,
    iid = TRUE
  )

#---leave NYPUM out----

Uno_3v.12 <-
  timeROC::timeROC(
    T = data12y.3v$year, 
    delta = data12y.3v$cens,
    marker = data12y.3v$lp.3.12,
    cause = 1, 
    weighting = "marginal", 
    times = 9.99,
    iid = TRUE
  )


#---leave PICNICS out----

Uno_5v.12 <-
  timeROC::timeROC(
    T = data12y.5v$year, 
    delta = data12y.5v$cens,
    marker = data12y.5v$lp.5.12,
    cause = 1, 
    weighting = "marginal", 
    times = 9.99,
    iid = TRUE
  )

#---leave PINE out----

Uno_6v.12 <-
  timeROC::timeROC(
    T = data12y.6v$year, 
    delta = data12y.6v$cens,
    marker = data12y.6v$lp.6.12,
    cause = 1, 
    weighting = "marginal", 
    times = 9.99,
    iid = TRUE
  )


Uno_1v.12
Uno_3v.12
Uno_5v.12
Uno_6v.12
```


```{r Mean calibration 10 years}

# Observed / Expected ratio
alpha <- .05

#---leave CamPalGN out----

# Observed
obj.1.12 <- summary(survfit(
  Surv(year, cens) ~ 1, 
  data = data12y.1v),
  times = 10)

obs_t.1.12 <- 1 - obj.1.12$surv

data12y.1v$pred<-predict(model1.12,newdata = data12y.1v,type = "survival",times = 10)[[2]]  #survival probabilities

# Expected
exp_t.1.12 <-mean(1-data12y.1v$pred) #predicts risk, as 1 - S(t|X)


# Observed / Expected ratio
OE_t.1.12 <- obs_t.1.12 / exp_t.1.12

OE_summary.1.12 <- c(
  "OE" = OE_t.1.12,
  "2.5 %" = OE_t.1.12 * exp(-qnorm(1 - alpha / 2) * sqrt(1 / obj.1.12$n.event)),
  "97.5 %" = OE_t.1.12 * exp(+qnorm(1 - alpha / 2) * sqrt(1 / obj.1.12$n.event))
)

OE_summary.1.12


#---leave NYPUM out----

obj.3.12 <- summary(survfit(
  Surv(year, cens) ~ 1, 
  data = data12y.3v),
  times = 10)

obs_t.3.12 <- 1 - obj.3.12$surv

data12y.3v$pred<-predict(model3.12,newdata = data12y.3v,type = "survival",times = 10)[[2]]  #survival probabilities

# Expected
exp_t.3.12 <-mean(1-data12y.3v$pred) #predicts risk, as 1 - S(t|X)


# Observed / Expected ratio
OE_t.3.12 <- obs_t.3.12 / exp_t.3.12

OE_summary.3.12 <- c(
  "OE" = OE_t.3.12,
  "2.5 %" = OE_t.3.12 * exp(-qnorm(1 - alpha / 2) * sqrt(1 / obj.3.12$n.event)),
  "97.5 %" = OE_t.3.12 * exp(+qnorm(1 - alpha / 2) * sqrt(1 / obj.3.12$n.event))
)

OE_summary.3.12

#---leave PICNICS out----

obj.5.12 <- summary(survfit(
  Surv(year, cens) ~ 1, 
  data = data12y.5v),
  times = 10)

obs_t.5.12 <- 1 - obj.5.12$surv

data12y.5v$pred<-predict(model5.12,newdata = data12y.5v,type = "survival",times = 10)[[2]]  #survival probabilities

# Expected
exp_t.5.12 <-mean(1-data12y.5v$pred) #predicts risk, as 1 - S(t|X)


# Observed / Expected ratio
OE_t.5.12 <- obs_t.5.12 / exp_t.5.12

OE_summary.5.12 <- c(
  "OE" = OE_t.5.12,
  "2.5 %" = OE_t.5.12 * exp(-qnorm(1 - alpha / 2) * sqrt(1 / obj.5.12$n.event)),
  "97.5 %" = OE_t.5.12 * exp(+qnorm(1 - alpha / 2) * sqrt(1 / obj.5.12$n.event))
)

OE_summary.5.12

#---leave PINE out----

obj.6.12 <- summary(survfit(
  Surv(year, cens) ~ 1, 
  data = data12y.6v),
  times = 10)

obs_t.6.12 <- 1 - obj.6.12$surv

data12y.6v$pred<-predict(model6.12,newdata = data12y.6v,type = "survival",times = 10)[[2]]  #survival probabilities

# Expected
exp_t.6.12 <-mean(1-data12y.6v$pred) #predicts risk, as 1 - S(t|X)


# Observed / Expected ratio
OE_t.6.12 <- obs_t.6.12 / exp_t.6.12

OE_summary.6.12 <- c(
  "OE" = OE_t.6.12,
  "2.5 %" = OE_t.6.12 * exp(-qnorm(1 - alpha / 2) * sqrt(1 / obj.6.12$n.event)),
  "97.5 %" = OE_t.6.12 * exp(+qnorm(1 - alpha / 2) * sqrt(1 / obj.6.12$n.event))
)

OE_summary.6.12
```


```{r  Moderate calibration 10 years}

#moderate calibration uses smooth curves of predicted risk from a more complex ‘secondary’ Cox model against the predicted risk from the development model 


#---leave CamPalGN out----

#data10y.1v$pred<-predict(model1.10,newdata = data10y.1v,type = "survival",times = 7)[[2]]  #survival probabilities

# predicted risk

data12y.1v$risk <-(1-data12y.1v$pred) #predicted risk, as 1 - S(t|X),the probabilities of events

data12y.1v$risk.cll <- log(-log(1-data12y.1v$risk)) #complementary log-log link

#Check location of knots again

data12y.1v%>%
  filter(cens==1)%>%  #cens==1 event
  summarise(max(year),min(year))  


# Estimate actual risk

vcal.1.12.RP <- flexsurvspline(Surv(year, cens)~rcs(risk.cll,3), data = data12y.1v, k=1,bknots = c(log(1.147159),log(9.040383)),scale = "odds")




#survest function is to estimate survival probabilities

dat_cal.1.12 <- cbind.data.frame(
  "obs" = 1 - predict(vcal.1.12.RP,
                      type = "survival",
                      times = 10,
                      newdata = data12y.1v)[[2]], #1-s(t=4) to get the refitted model predicted risk
  
  "lower" = 1 - predict(vcal.1.12.RP,
                      type = "survival",
                      conf.int = T,
                      times = 10,
                      newdata = data12y.1v)[[4]],
  
  "upper" = 1 - predict(vcal.1.12.RP,
                      type = "survival",
                      conf.int = T,
                      times = 10,
                      newdata = data12y.1v)[[3]],
  "pred" = data12y.1v$risk
)


dat_cal.1.12 <- dat_cal.1.12[order(dat_cal.1.12$pred), ]

png("Cam-10y.png",width = 3500,height =2000,res = 400)
par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.1.12$pred, #x is predicted risk from the 
  y=dat_cal.1.12$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model",
  ylab = "Predicted risk from refitted model",  
  main = "Validation dataset is CamPalGN",
  bty = "n" #no box
)

lines(dat_cal.1.12$pred, 
      dat_cal.1.12$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.1.12$pred, 
      dat_cal.1.12$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("topleft",
        c("Ideal calibration",
          "Calibration curve based on secondary Royston-Parmar model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.8)
dev.off()

# Numerical measures
absdiff_cph.1.12 <- abs(dat_cal.1.12$pred - dat_cal.1.12$obs)

numsum_cph.1.12 <- c(
  "ICI" = mean(absdiff_cph.1.12),
  setNames(quantile(absdiff_cph.1.12, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.1.12)
)
numsum_cph.1.12



#---leave NYPUM out----

# predicted risk

data12y.3v$risk <-(1-data12y.3v$pred) #predicted risk, as 1 - S(t|X),the probabilities of events

data12y.3v$risk.cll <- log(-log(1-data12y.3v$risk)) #complementary log-log link

#Check location of knots again

data12y.3v%>%
  filter(cens==1)%>%  #cens==1 event
  summarise(max(year),min(year))  


# Estimate actual risk

vcal.3.12.RP <- flexsurvspline(Surv(year, cens) ~ rcs(risk.cll,3), data = data12y.3v, k=1,bknots = c(log(0.8925394),log(9.511294)),scale = "odds")


dat_cal.3.12 <- cbind.data.frame(
  "obs" = 1 - predict(vcal.3.12.RP,
                      type = "survival",
                      times = 10,
                      newdata = data12y.3v)[[2]], #1-s(t=4) to get the refitted model predicted risk
  
  "lower" = 1 - predict(vcal.3.12.RP,
                      type = "survival",
                      conf.int = T,
                      times = 10,
                      newdata = data12y.3v)[[4]],
  
  "upper" = 1 - predict(vcal.3.12.RP,
                      type = "survival",
                      conf.int = T,
                      times = 10,
                      newdata = data12y.3v)[[3]],
  "pred" = data12y.3v$risk
)


dat_cal.3.12 <- dat_cal.3.12[order(dat_cal.3.12$pred), ]

png("NY-10y.png",width = 3500,height =2000,res = 400)
par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.3.12$pred, #x is predicted risk from the 
  y=dat_cal.3.12$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model",
  ylab = "Predicted risk from refitted model",  
  main = "Validation dataset is NYPUM",
  bty = "n" #no box
)

lines(dat_cal.3.12$pred, 
      dat_cal.3.12$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.3.12$pred, 
      dat_cal.3.12$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("topleft",
        c("Ideal calibration",
          "Calibration curve based on secondary Royston-Parmar model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.75)
dev.off()
# Numerical measures
absdiff_cph.3.12 <- abs(dat_cal.3.12$pred - dat_cal.3.12$obs)

numsum_cph.3.12 <- c(
  "ICI" = mean(absdiff_cph.3.12),
  setNames(quantile(absdiff_cph.3.12, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.3.12)
)
numsum_cph.3.12

#---leave PICNICS out----

data12y.5v$risk <-(1-data12y.5v$pred) #predicted risk, as 1 - S(t|X),the probabilities of events

data12y.5v$risk.cll <- log(-log(1-data12y.5v$risk)) #complementary log-log link

#Check location of knots again

data12y.5v%>%
  filter(cens==1)%>%  #cens==1 event
  summarise(max(year),min(year))  


# Estimate actual risk

vcal.5.12.RP <- flexsurvspline(Surv(year, cens) ~ rcs(risk.cll,3), data = data10y.5v, k=1,bknots = c(log(0.1067762),log(9.943874)),scale = "odds")


dat_cal.5.12 <- cbind.data.frame(
  "obs" = 1 - predict(vcal.5.12.RP,
                      type = "survival",
                      times = 10,
                      newdata = data12y.5v)[[2]], #1-s(t=4) to get the refitted model predicted risk
  
  "lower" = 1 - predict(vcal.5.12.RP,
                      type = "survival",
                      conf.int = T,
                      times = 10,
                      newdata = data12y.5v)[[4]],
  
  "upper" = 1 - predict(vcal.5.12.RP,
                      type = "survival",
                      conf.int = T,
                      times = 10,
                      newdata = data12y.5v)[[3]],
  "pred" = data12y.5v$risk
)


dat_cal.5.12 <- dat_cal.5.12[order(dat_cal.5.12$pred), ]

png("PIC-10y.png",width = 3500,height =2000,res = 400)
par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.5.12$pred, #x is predicted risk from the 
  y=dat_cal.5.12$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model",
  ylab = "Predicted risk from refitted model",  
  main = "Validation dataset is PICNICS",
  bty = "n" #no box
)

lines(dat_cal.5.12$pred, 
      dat_cal.5.12$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.5.12$pred, 
      dat_cal.5.12$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("topleft",
        c("Ideal calibration",
          "Calibration curve based on secondary Royston-Parmar model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.75)
dev.off()

# Numerical measures
absdiff_cph.5.12 <- abs(dat_cal.5.12$pred - dat_cal.5.12$obs)

numsum_cph.5.12 <- c(
  "ICI" = mean(absdiff_cph.5.12),
  setNames(quantile(absdiff_cph.5.12, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.5.12)
)
numsum_cph.5.12

#---leave PINE out----

data12y.6v$risk <-(1-data12y.6v$pred) #predicted risk, as 1 - S(t|X),the probabilities of events

data12y.6v$risk.cll <- log(-log(1-data12y.6v$risk)) #complementary log-log link

#Check location of knots again

data12y.6v%>%
  filter(cens==1)%>%  #cens==1 event
  summarise(max(year),min(year))  


# Estimate actual risk

vcal.6.12.RP <- flexsurvspline(Surv(year, cens) ~ rcs(risk.cll,3), data = data12y.6v, k=1,bknots = c(log(0.5557837),log(9.596167)),scale = "odds")


dat_cal.6.12 <- cbind.data.frame(
  "obs" = 1 - predict(vcal.6.12.RP,
                      type = "survival",
                      times = 10,
                      newdata = data12y.6v)[[2]], #1-s(t=4) to get the refitted model predicted risk
  
  "lower" = 1 - predict(vcal.6.12.RP,
                      type = "survival",
                      conf.int = T,
                      times = 10,
                      newdata = data12y.6v)[[4]],
  
  "upper" = 1 - predict(vcal.6.12.RP,
                      type = "survival",
                      conf.int = T,
                      times = 10,
                      newdata = data12y.6v)[[3]],
  "pred" = data12y.6v$risk
)


dat_cal.6.12 <- dat_cal.6.12[order(dat_cal.6.12$pred), ]

png("PIN-10y.png",width = 3500,height =2000,res = 400)
par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.6.12$pred, #x is predicted risk from the 
  y=dat_cal.6.12$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model",
  ylab = "Predicted risk from refitted model",  
  main = "Validation dataset is PINE",
  bty = "n" #no box
)

lines(dat_cal.6.12$pred, 
      dat_cal.6.12$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.6.12$pred, 
      dat_cal.6.12$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("topleft",
        c("Ideal calibration",
          "Calibration curve based on secondary Royston-Parmar model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.85)
dev.off()

# Numerical measures
absdiff_cph.6.12 <- abs(dat_cal.6.12$pred - dat_cal.6.12$obs)

numsum_cph.6.12 <- c(
  "ICI" = mean(absdiff_cph.6.12),
  setNames(quantile(absdiff_cph.6.12, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.6.12)
)
numsum_cph.6.12

```


```{r Weak calibration 10 years}

#Include linear predictor in validation datasets as a predictor

#---leave CamPalGN out----

vcal.1.12.weak <- flexsurvspline(Surv(year, cens) ~risk.cll, data = data12y.1v, k=1,bknots = c(log(1.147159),log(9.040383)),scale = "odds")

data12y.1v$pred.act<-predict(vcal.1.12.weak,type = "survival",times = 10,newdata = data12y.1v)[[2]] #actual survival 
data12y.1v$g_st<-log((1/data12y.1v$pred.act)-1)
val.1.12<-lm(g_st~lp.1.12,data = data12y.1v)

#lm(g_st~log((1/data12y.1v$pred)-1),data = data12y.1v)


summary(val.1.12)

calslope_summary.1.12 <- c(
  "calibration slope" = val.1.12$coefficients[2],
  "2.5 %"  = val.1.12$coefficients[2] - 1.96 * 0.01731,
  "97.5 %" = val.1.12$coefficients[2] + 1.96 * 0.01731
)
calslope_summary.1.12

#---leave NYPUM out----

vcal.3.12.weak <- flexsurvspline(Surv(year, cens) ~risk.cll, data = data12y.3v, k=1,bknots = c(log(0.8925394), log(9.511294)),scale = "odds")

data12y.3v$pred.act<-predict(vcal.3.12.weak,type = "survival",times = 10,newdata = data12y.3v)[[2]] #actual survival 
data12y.3v$g_st<-log((1/data12y.3v$pred.act)-1)
val.3.12<-lm(g_st~lp.3.12,data = data12y.3v)

summary(val.3.12)

calslope_summary.3.12 <- c(
  "calibration slope" = val.3.12$coefficients[2],
  "2.5 %"  = val.3.12$coefficients[2] - 1.96 * 0.01887,
  "97.5 %" = val.3.12$coefficients[2] + 1.96 * 0.01887
)
calslope_summary.3.12


#---leave PICNICS out----

vcal.5.12.weak <- flexsurvspline(Surv(year, cens) ~risk.cll, data = data12y.5v, k=1,bknots = c(log(0.1067762), log(9.943874)),scale = "odds")


data12y.5v$pred.act<-predict(vcal.5.12.weak,type = "survival",times = 10,newdata = data12y.5v)[[2]] #actual survival 
data12y.5v$g_st<-log((1/data12y.5v$pred.act)-1)
val.5.12<-lm(g_st~lp.5.12,data = data12y.5v)

summary(val.5.12)

calslope_summary.5.12 <- c(
  "calibration slope" = val.5.12$coefficients[2],
  "2.5 %"  = val.5.12$coefficients[2] - 1.96 * 0.009372,
  "97.5 %" = val.5.12$coefficients[2] + 1.96 * 0.009372
)
calslope_summary.5.12

#---leave PINE out----

vcal.6.12.weak <- flexsurvspline(Surv(year, cens) ~risk.cll, data = data12y.6v, k=1,bknots = c(log(0.5557837), log(9.596167)),scale = "odds")


data12y.6v$pred.act<-predict(vcal.6.12.weak,type = "survival",times = 10,newdata = data12y.6v)[[2]] #actual survival 
data12y.6v$g_st<-log((1/data12y.6v$pred.act)-1)
val.6.12<-lm(g_st~lp.6.12,data = data12y.6v)

summary(val.6.12)

calslope_summary.6.12 <- c(
  "calibration slope" = val.6.12$coefficients[2],
  "2.5 %"  = val.6.12$coefficients[2] - 1.96 * 0.01169,
  "97.5 %" = val.6.12$coefficients[2] + 1.96 * 0.01169
)
calslope_summary.6.12
```


```{r  recalibration 10 year}

#----CamPalGN-----

model1.12.re<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal,data=data12y.1,k=1,bknots = c(log(1.147159),log(9.040383)),scale = "odds")  #change the knots position

rcs.mod1.12<-as.data.frame(basis(model1.12.re$knots,log(10))) #basis spline
data12y.1v$rcs1<-rcs.mod1.12[,2]
data12y.1v$rcs2<-rcs.mod1.12[,3]

log((1-obj.1.12$surv)/mean(1-data12y.1v$pred)) #ln mean O/E risk ratio 

model1.12.re$res[c("gamma0", "gamma1", "gamma2"), "est"]

data12y.1v$pred.re<-1/(1+exp(-10.9104500-0.5297541+1.6319907*data12y.1v$rcs1-0.9665124*data12y.1v$rcs2+data12y.1v$lp.1.12)) #change the knots position and s(lnt;r) but keep the linear predictor the same

(1-obj.1.12$surv)/mean(1-data12y.1v$pred.re) #Mean calibration improve
#Before is (1-obj.1.12$surv)/mean(1-data12y.1v$pred), 0.59, now is 0.78

data12y.1v$risk.re<-1-data12y.1v$pred.re

dat_cal.1.12.RP.re <- cbind.data.frame(
  "obs" = 1 - predict(vcal.1.12.RP,
                      type = "survival",
                      times = 10,
                      newdata = data12y.1v)[[2]], #1-s(t=4) to get the refitted model predicted risk
  
  "lower" = 1 - predict(vcal.1.12.RP,
                        type = "survival",
                        conf.int = T,
                        times = 10,
                        newdata = data12y.1v)[[4]],
  
  "upper" = 1 - predict(vcal.1.12.RP,
                        type = "survival",
                        conf.int = T,
                        times = 10,
                        newdata = data12y.1v)[[3]],
  "pred" = data12y.1v$risk.re
)


dat_cal.1.12.RP.re <- dat_cal.1.12.RP.re[order(dat_cal.1.12.RP.re$pred), ]

png("Cam-10y-re1.png",width = 3500,height =2000,res = 400)
par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.1.12.RP.re$pred, #x is predicted risk from the 
  y=dat_cal.1.12.RP.re$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model with new boundary knots position and intercept",
  ylab = "Predicted risk from refitted model",  
  main = "Validation dataset is CamPalGN",
  bty = "n" #no box
)

lines(dat_cal.1.12.RP.re$pred, 
      dat_cal.1.12.RP.re$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.1.12.RP.re$pred, 
      dat_cal.1.12.RP.re$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("topleft",
        c("Ideal calibration",
          "Calibration curve based on secondary Royston-Parmar model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.8)
dev.off()

# Numerical measures
absdiff_cph.1.12.RP.re <- abs(dat_cal.1.12.RP.re$pred - dat_cal.1.12.RP.re$obs)

numsum_cph.1.12.RP.re <- c(
  "ICI" = mean(absdiff_cph.1.12.RP.re),
  setNames(quantile(absdiff_cph.1.12.RP.re, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.1.12.RP.re)
)
numsum_cph.1.12.RP.re

#----NYPUM-----

model3.12.re<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal,data=data12y.3,k=1,bknots = c(log(0.8925394),log(9.511294)),scale = "odds")  #change the knots position

rcs.mod3.12<-as.data.frame(basis(model3.12.re$knots,log(10))) #basis spline
data12y.3v$rcs1<-rcs.mod3.12[,2]
data12y.3v$rcs2<-rcs.mod3.12[,3]

log((1-obj.3.12$surv)/mean(1-data12y.3v$pred)) #ln mean O/E risk ratio 

model3.12.re$res[c("gamma0", "gamma1", "gamma2"), "est"]

data12y.3v$pred.re<-1/(1+exp(-9.980246+0.2426892+1.511023*data12y.3v$rcs1-0.733772*data12y.3v$rcs2+data12y.3v$lp.3.12)) #change the knots position and s(lnt;r) but keep the linear predictor the same

(1-obj.3.12$surv)/mean(1-data12y.3v$pred.re) #Mean calibration improve
#Before is (1-obj.3.12$surv)/mean(1-data12y.3v$pred), 1.27, now is 1.21

data12y.3v$risk.re<-1-data12y.3v$pred.re

dat_cal.3.12.RP.re <- cbind.data.frame(
  "obs" = 1 - predict(vcal.3.12.RP,
                      type = "survival",
                      times = 10,
                      newdata = data12y.3v)[[2]], #1-s(t=4) to get the refitted model predicted risk
  
  "lower" = 1 - predict(vcal.3.12.RP,
                        type = "survival",
                        conf.int = T,
                        times = 10,
                        newdata = data12y.3v)[[4]],
  
  "upper" = 1 - predict(vcal.3.12.RP,
                        type = "survival",
                        conf.int = T,
                        times = 10,
                        newdata = data12y.3v)[[3]],
  "pred" = data12y.3v$risk.re
)


dat_cal.3.12.RP.re <- dat_cal.3.12.RP.re[order(dat_cal.3.12.RP.re$pred), ]

png("NY-10y-re1.png",width = 3500,height =2000,res = 400)
par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.3.12.RP.re$pred, #x is predicted risk from the 
  y=dat_cal.3.12.RP.re$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model with new boundary knots position and intercept",
  ylab = "Predicted risk from refitted model",  
  main = "Validation study is NYPUM",
  bty = "n" #no box
)

lines(dat_cal.3.12.RP.re$pred, 
      dat_cal.3.12.RP.re$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.3.12.RP.re$pred, 
      dat_cal.3.12.RP.re$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("topleft",
        c("Ideal calibration",
          "Calibration curve based on secondary Royston-Parmar model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.8)
dev.off()

# Numerical measures
absdiff_cph.3.12.RP.re <- abs(dat_cal.3.12.RP.re$pred - dat_cal.3.12.RP.re$obs)

numsum_cph.3.12.RP.re <- c(
  "ICI" = mean(absdiff_cph.3.12.RP.re),
  setNames(quantile(absdiff_cph.3.12.RP.re, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.3.12.RP.re)
)
numsum_cph.3.12.RP.re

#----PICNICS----

model5.12.re<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal,data=data12y.5,k=1,bknots = c(log(0.1067762),log(9.943874)),scale = "odds")  #change the knots position

rcs.mod5.12<-as.data.frame(basis(model5.12.re$knots,log(10))) #basis spline
data12y.5v$rcs1<-rcs.mod5.12[,2]
data12y.5v$rcs2<-rcs.mod5.12[,3]

log((1-obj.5.12$surv)/mean(1-data12y.5v$pred)) #ln mean O/E risk ratio 

model5.12.re$res[c("gamma0", "gamma1", "gamma2"), "est"]

data12y.5v$pred.re<-1/(1+exp(-10.2478365-0.1813029+1.3102989*data12y.5v$rcs1-0.2546462*data12y.5v$rcs2+data12y.5v$lp.5.12)) #change the knots position and s(lnt;r) but keep the linear predictor the same

(1-obj.5.12$surv)/mean(1-data12y.5v$pred.re) #Mean calibration improve
#Before is 0.83, now is 0.89

data12y.5v$risk.re<-1-data12y.5v$pred.re

dat_cal.5.12.RP.re <- cbind.data.frame(
  "obs" = 1 - predict(vcal.5.12.RP,
                      type = "survival",
                      times = 10,
                      newdata = data12y.5v)[[2]], #1-s(t=4) to get the refitted model predicted risk
  
  "lower" = 1 - predict(vcal.5.12.RP,
                        type = "survival",
                        conf.int = T,
                        times = 10,
                        newdata = data12y.5v)[[4]],
  
  "upper" = 1 - predict(vcal.5.12.RP,
                        type = "survival",
                        conf.int = T,
                        times = 10,
                        newdata = data12y.5v)[[3]],
  "pred" = data12y.5v$risk.re
)


dat_cal.5.12.RP.re <- dat_cal.5.12.RP.re[order(dat_cal.5.12.RP.re$pred), ]

png("PIC-10y-re1.png",width = 3500,height =2000,res = 400)
par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.5.12.RP.re$pred, #x is predicted risk from the 
  y=dat_cal.5.12.RP.re$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model with new boundary knots position and intercept",
  ylab = "Predicted risk from refitted model",  
  main = "Validation dataset is PICNICS",
  bty = "n" #no box
)

lines(dat_cal.5.12.RP.re$pred, 
      dat_cal.5.12.RP.re$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.5.12.RP.re$pred, 
      dat_cal.5.12.RP.re$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend(0,1,
        c("Ideal calibration",
          "Calibration curve based on secondary Royston-Parmar model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.7)
dev.off()

# Numerical measures
absdiff_cph.5.12.RP.re <- abs(dat_cal.5.12.RP.re$pred - dat_cal.5.12.RP.re$obs)

numsum_cph.5.12.RP.re <- c(
  "ICI" = mean(absdiff_cph.5.12.RP.re),
  setNames(quantile(absdiff_cph.5.12.RP.re, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.5.12.RP.re)
)
numsum_cph.5.12.RP.re


#----PINE----

model6.12.re<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl+mmsebltotal,data=data12y.6,k=1,bknots = c(log(0.5557837),log(9.596167)),scale = "odds")  #change the knots position

rcs.mod6.12<-as.data.frame(basis(model6.12.re$knots,log(10))) #basis spline
data12y.6v$rcs1<-rcs.mod6.12[,2]
data12y.6v$rcs2<-rcs.mod6.12[,3]

log((1-obj.6.12$surv)/mean(1-data12y.6v$pred)) #ln mean O/E risk ratio 

model6.12.re$res[c("gamma0", "gamma1", "gamma2"), "est"]

data12y.6v$pred.re<-1/(1+exp(-15.6610870-0.1367301+1.4051660*data12y.6v$rcs1-0.8035063*data12y.6v$rcs2+data12y.6v$lp.6.12)) #change the knots position and s(lnt;r) but keep the linear predictor the same

(1-obj.6.12$surv)/mean(1-data12y.6v$pred.re) #Mean calibration improve
#Before is 0.87, now is 0.92

data12y.6v$risk.re<-1-data12y.6v$pred.re

dat_cal.6.12.RP.re <- cbind.data.frame(
  "obs" = 1 - predict(vcal.6.12.RP,
                      type = "survival",
                      times = 10,
                      newdata = data12y.6v)[[2]], #1-s(t=4) to get the refitted model predicted risk
  
  "lower" = 1 - predict(vcal.6.12.RP,
                        type = "survival",
                        conf.int = T,
                        times = 10,
                        newdata = data12y.6v)[[4]],
  
  "upper" = 1 - predict(vcal.6.12.RP,
                        type = "survival",
                        conf.int = T,
                        times = 10,
                        newdata = data12y.6v)[[3]],
  "pred" = data12y.6v$risk.re
)


dat_cal.6.12.RP.re <- dat_cal.6.12.RP.re[order(dat_cal.6.12.RP.re$pred), ]

png("PIN-10y-re1.png",width = 3500,height =2000,res = 400)
par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.6.12.RP.re$pred, #x is predicted risk from the 
  y=dat_cal.6.12.RP.re$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model with new boundary knots position and intercept",
  ylab = "Predicted risk from refitted model",  
  main = "Validation dataset is PINE",
  bty = "n" #no box
)

lines(dat_cal.6.12.RP.re$pred, 
      dat_cal.6.12.RP.re$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.6.12.RP.re$pred, 
      dat_cal.6.12.RP.re$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("topleft",
        c("Ideal calibration",
          "Calibration curve based on secondary Royston-Parmar model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.8)
dev.off()

# Numerical measures
absdiff_cph.6.12.RP.re <- abs(dat_cal.6.12.RP.re$pred - dat_cal.6.12.RP.re$obs)

numsum_cph.6.12.RP.re <- c(
  "ICI" = mean(absdiff_cph.6.12.RP.re),
  setNames(quantile(absdiff_cph.6.12.RP.re, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.6.12.RP.re)
)
numsum_cph.6.12.RP.re

```

```{r recalibration2 times slope}

#-----CamPalGN-------

summary(val.1.12)

data12y.1v$pred.re.1<-1/(1+exp(-10.9104500-0.5297541-1.638+1.6319907*data12y.1v$rcs1-0.9665124*data12y.1v$rcs2+1.253*data12y.1v$lp.1.12)) 

(1-obj.1.12$surv)/mean(1-data12y.1v$pred.re.1) #Mean calibration improve
#Before is (1-obj.1.12$surv)/mean(1-data12y.1v$pred.re),from 0.79 to now 0.88

data12y.1v$risk.re.1<-1-data12y.1v$pred.re.1

dat_cal.1.12.RP.re.1 <- cbind.data.frame(
  "obs" = 1 - predict(vcal.1.12.RP,
                      type = "survival",
                      times = 10,
                      newdata = data12y.1v)[[2]], #1-s(t=4) to get the refitted model predicted risk
  
  "lower" = 1 - predict(vcal.1.12.RP,
                        type = "survival",
                        conf.int = T,
                        times = 10,
                        newdata = data12y.1v)[[4]],
  
  "upper" = 1 - predict(vcal.1.12.RP,
                        type = "survival",
                        conf.int = T,
                        times = 10,
                        newdata = data12y.1v)[[3]],
  "pred" = data12y.1v$risk.re.1
)


dat_cal.1.12.RP.re.1 <- dat_cal.1.12.RP.re.1[order(dat_cal.1.12.RP.re.1$pred), ]

png("Cam-10y-re2.png",width = 3500,height =2000,res = 400)
par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.1.12.RP.re.1$pred, #x is predicted risk from the 
  y=dat_cal.1.12.RP.re.1$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model with new boundary knots position and intercept and coefficients",
  ylab = "Predicted risk from refitted model",  
  main = "Validation dataset is CamPalGN",
  bty = "n" #no box
)

lines(dat_cal.1.12.RP.re.1$pred, 
      dat_cal.1.12.RP.re.1$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.1.12.RP.re.1$pred, 
      dat_cal.1.12.RP.re.1$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("topleft",
        c("Ideal calibration",
          "Calibration curve based on secondary Royston-Parmar model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.8)
dev.off()

# Numerical measures
absdiff_cph.1.12.RP.re.1 <- abs(dat_cal.1.12.RP.re.1$pred - dat_cal.1.12.RP.re.1$obs)

numsum_cph.1.12.RP.re.1 <- c(
  "ICI" = mean(absdiff_cph.1.12.RP.re.1),
  setNames(quantile(absdiff_cph.1.12.RP.re.1, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.1.12.RP.re.1)
)
numsum_cph.1.12.RP.re.1



#-----NYPUM----

#summary(val.3.12)

data12y.3v$pred.re.1<-1/(1+exp(-9.980246+0.2426892-0.402+1.511023*data12y.3v$rcs1-0.733772*data12y.3v$rcs2+1.287*data12y.3v$lp.3.12)) 

(1-obj.3.12$surv)/mean(1-data12y.3v$pred.re.1) #Mean calibration improve
#Before is (1-obj.3.12$surv)/mean(1-data12y.3v$pred.re) from 1.21 to 0.94

data12y.3v$risk.re.1<-1-data12y.3v$pred.re.1

dat_cal.3.12.RP.re.1 <- cbind.data.frame(
  "obs" = 1 - predict(vcal.3.12.RP,
                      type = "survival",
                      times = 10,
                      newdata = data12y.3v)[[2]], #1-s(t=4) to get the refitted model predicted risk
  
  "lower" = 1 - predict(vcal.3.12.RP,
                        type = "survival",
                        conf.int = T,
                        times = 10,
                        newdata = data12y.3v)[[4]],
  
  "upper" = 1 - predict(vcal.3.12.RP,
                        type = "survival",
                        conf.int = T,
                        times = 10,
                        newdata = data12y.3v)[[3]],
  "pred" = data12y.3v$risk.re.1
)


dat_cal.3.12.RP.re.1 <- dat_cal.3.12.RP.re.1[order(dat_cal.3.12.RP.re.1$pred), ]

png("NY-10y-re2.png",width = 3500,height =2000,res = 400)
par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.3.12.RP.re.1$pred, #x is predicted risk from the 
  y=dat_cal.3.12.RP.re.1$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model with new boundary knots position and intercept and coefficients",
  ylab = "Predicted risk from refitted model", 
  main = "Validation dataset is NYPUM",
  bty = "n" #no box
)

lines(dat_cal.3.12.RP.re.1$pred, 
      dat_cal.3.12.RP.re.1$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.3.12.RP.re.1$pred, 
      dat_cal.3.12.RP.re.1$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("topleft",
        c("Ideal calibration",
          "Calibration curve based on secondary Royston-Parmar model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.8)
dev.off()

# Numerical measures
absdiff_cph.3.12.RP.re.1 <- abs(dat_cal.3.12.RP.re.1$pred - dat_cal.3.12.RP.re.1$obs)

numsum_cph.3.12.RP.re.1 <- c(
  "ICI" = mean(absdiff_cph.3.12.RP.re.1),
  setNames(quantile(absdiff_cph.3.12.RP.re.1, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.3.12.RP.re.1)
)
numsum_cph.3.12.RP.re.1



#----PICNICS----

summary(val.5.12)

data12y.5v$pred.re.1<-1/(1+exp(-10.2478365-0.1813029-0.564+1.3102989*data12y.5v$rcs1-0.2546462*data12y.5v$rcs2+1.124*data12y.5v$lp.5.12))

(1-obj.5.12$surv)/mean(1-data12y.5v$pred.re.1) #Mean calibration improve
#Before 0.89 now 0.92

data12y.5v$risk.re.1<-1-data12y.5v$pred.re.1

dat_cal.5.12.RP.re.1 <- cbind.data.frame(
  "obs" = 1 - predict(vcal.5.12.RP,
                      type = "survival",
                      times = 10,
                      newdata = data12y.5v)[[2]], #1-s(t=4) to get the refitted model predicted risk
  
  "lower" = 1 - predict(vcal.5.12.RP,
                        type = "survival",
                        conf.int = T,
                        times = 10,
                        newdata = data12y.5v)[[4]],
  
  "upper" = 1 - predict(vcal.5.12.RP,
                        type = "survival",
                        conf.int = T,
                        times = 10,
                        newdata = data12y.5v)[[3]],
  "pred" = data12y.5v$risk.re.1
)


dat_cal.5.12.RP.re.1 <- dat_cal.5.12.RP.re.1[order(dat_cal.5.12.RP.re.1$pred), ]

png("PIC-10y-re2.png",width = 3500,height =2000,res = 400)
par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.5.12.RP.re.1$pred, #x is predicted risk from the 
  y=dat_cal.5.12.RP.re.1$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model with new boundary knots position and intercept and coefficients",
  ylab = "Predicted risk from refitted model",  
  main = "Validation dataset is PICNICS",
  bty = "n" #no box
)

lines(dat_cal.5.12.RP.re.1$pred, 
      dat_cal.5.12.RP.re.1$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.5.12.RP.re.1$pred, 
      dat_cal.5.12.RP.re.1$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("topleft",
        c("Ideal calibration",
          "Calibration curve based on secondary Royston-Parmar model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.7)
dev.off()

# Numerical measures
absdiff_cph.5.12.RP.re.1 <- abs(dat_cal.5.12.RP.re.1$pred - dat_cal.5.12.RP.re.1$obs)

numsum_cph.5.12.RP.re.1 <- c(
  "ICI" = mean(absdiff_cph.5.12.RP.re.1),
  setNames(quantile(absdiff_cph.5.12.RP.re.1, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.5.12.RP.re.1)
)
numsum_cph.5.12.RP.re.1

#----PINE-----

summary(val.6.12)

data12y.6v$pred.re.1<-1/(1+exp(-15.6610870-0.1367301+1.546+1.4051660*data12y.6v$rcs1-0.8035063*data12y.6v$rcs2+0.843*data12y.6v$lp.6.12))

(1-obj.6.12$surv)/mean(1-data12y.6v$pred.re.1) #Mean calibration improve
#Before is 0.92 now 0.93

data12y.6v$risk.re.1<-1-data12y.6v$pred.re.1

dat_cal.6.12.RP.re.1 <- cbind.data.frame(
  "obs" = 1 - predict(vcal.6.12.RP,
                      type = "survival",
                      times = 10,
                      newdata = data12y.6v)[[2]], #1-s(t=4) to get the refitted model predicted risk
  
  "lower" = 1 - predict(vcal.6.12.RP,
                        type = "survival",
                        conf.int = T,
                        times = 10,
                        newdata = data12y.6v)[[4]],
  
  "upper" = 1 - predict(vcal.6.12.RP,
                        type = "survival",
                        conf.int = T,
                        times = 10,
                        newdata = data12y.6v)[[3]],
  "pred" = data12y.6v$risk.re.1
)


dat_cal.6.12.RP.re.1 <- dat_cal.6.12.RP.re.1[order(dat_cal.6.12.RP.re.1$pred), ]

png("PIN-10y-re2.png",width = 3500,height =2000,res = 400)
par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.6.12.RP.re.1$pred, #x is predicted risk from the 
  y=dat_cal.6.12.RP.re.1$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model with new boundary knots position and intercept and coefficients",
  ylab = "Predicted risk from refitted model",  
  main = "Validation dataset is PINE",
  bty = "n" #no box
)

lines(dat_cal.6.12.RP.re.1$pred, 
      dat_cal.6.12.RP.re.1$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.6.12.RP.re.1$pred, 
      dat_cal.6.12.RP.re.1$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("topleft",
        c("Ideal calibration",
          "Calibration curve based on secondary Royston-Parmar model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.8)
dev.off()

# Numerical measures
absdiff_cph.6.12.RP.re.1 <- abs(dat_cal.6.12.RP.re.1$pred - dat_cal.6.12.RP.re.1$obs)

numsum_cph.6.12.RP.re.1 <- c(
  "ICI" = mean(absdiff_cph.6.12.RP.re.1),
  setNames(quantile(absdiff_cph.6.12.RP.re.1, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.6.12.RP.re.1)
)
numsum_cph.6.12.RP.re.1
```

```{r mean weak calibration after recalibration}

#----CamPalGN----

OE_t.1.12.re <- (1-obj.1.12$surv)/mean(1-data12y.1v$pred.re)

OE_summary.1.12.re <- c(
  "OE" = OE_t.1.12.re,
  "2.5 %" = OE_t.1.12.re * exp(-qnorm(1 - alpha / 2) * sqrt(1 / obj.1.12$n.event)),
  "97.5 %" = OE_t.1.12.re * exp(+qnorm(1 - alpha / 2) * sqrt(1 / obj.1.12$n.event))
)

OE_summary.1.12.re

data12y.1v$lp.1.12.re<-as.vector(as.matrix(des_matr1.12) %*% cbind(1.253*coef1.12))

val.1.12.re<-lm(g_st~lp.1.12.re,data = data12y.1v)

summary(val.1.12.re)

calslope_summary.1.12.re <- c(
  "calibration slope" = val.1.12.re$coefficients[2],
  "2.5 %"  =val.1.12.re$coefficients[2] - 1.96 *0.01381,
  "97.5 %" = val.1.12.re$coefficients[2] + 1.96 *0.01381
)

calslope_summary.1.12.re

#----NYPUM----

OE_t.3.12.re <- (1-obj.3.12$surv)/mean(1-data12y.3v$pred.re)

OE_summary.3.12.re <- c(
  "OE" = OE_t.3.12.re,
  "2.5 %" = OE_t.3.12.re * exp(-qnorm(1 - alpha / 2) * sqrt(1 / obj.3.12$n.event)),
  "97.5 %" = OE_t.3.12.re * exp(+qnorm(1 - alpha / 2) * sqrt(1 / obj.3.12$n.event))
)

OE_summary.3.12.re

data12y.3v$lp.3.12.re<-as.vector(as.matrix(des_matr3.12) %*% cbind(1.287*coef3.12))

val.3.12.re<-lm(g_st~lp.3.12.re,data = data12y.3v)

summary(val.3.12.re)

calslope_summary.3.12.re <- c(
  "calibration slope" = val.3.12.re$coefficients[2],
  "2.5 %"  =val.3.12.re$coefficients[2] - 1.96 *0.01467,
  "97.5 %" = val.3.12.re$coefficients[2] + 1.96 *0.01467
)

calslope_summary.3.12.re

#-----PICNICS-----

OE_t.5.12.re <- (1-obj.5.12$surv)/mean(1-data12y.5v$pred.re)

OE_summary.5.12.re <- c(
  "OE" = OE_t.5.12.re,
  "2.5 %" = OE_t.5.12.re * exp(-qnorm(1 - alpha / 2) * sqrt(1 / obj.5.12$n.event)),
  "97.5 %" = OE_t.5.12.re * exp(+qnorm(1 - alpha / 2) * sqrt(1 / obj.5.12$n.event))
)

OE_summary.5.12.re

data12y.5v$lp.5.12.re<-as.vector(as.matrix(des_matr5.12) %*% cbind(1.124*coef5.12))

val.5.12.re<-lm(g_st~lp.5.12.re,data = data12y.5v)

summary(val.5.12.re)

calslope_summary.5.12.re <- c(
  "calibration slope" = val.5.12.re$coefficients[2],
  "2.5 %"  =val.5.12.re$coefficients[2] - 1.96 *0.008338,
  "97.5 %" = val.5.12.re$coefficients[2] + 1.96 *0.008338
)

calslope_summary.5.12.re

#-----PINE-----

OE_t.6.12.re <- (1-obj.6.12$surv)/mean(1-data12y.6v$pred.re)

OE_summary.6.12.re <- c(
  "OE" = OE_t.6.12.re,
  "2.5 %" = OE_t.6.12.re * exp(-qnorm(1 - alpha / 2) * sqrt(1 / obj.6.12$n.event)),
  "97.5 %" = OE_t.6.12.re * exp(+qnorm(1 - alpha / 2) * sqrt(1 / obj.6.12$n.event))
)

OE_summary.6.12.re

data12y.6v$lp.6.12.re<-as.vector(as.matrix(des_matr6.12) %*% cbind(0.843*coef6.12))

val.6.12.re<-lm(g_st~lp.6.12.re,data = data12y.6v)

summary(val.6.12.re)

calslope_summary.6.12.re <- c(
  "calibration slope" = val.6.12.re$coefficients[2],
  "2.5 %"  =val.6.12.re$coefficients[2] - 1.96 *0.04086,
  "97.5 %" = val.6.12.re$coefficients[2] + 1.96 *0.04086
)

calslope_summary.6.12.re


```