---
title: "Fix model"
output: html_document
date: '2022-10-25'
---

#As we can see that the recalibration didn't work well in PINE, but other 5 studies all got improve.
#PINE only got improve in mean calibration but not in others
#Therefore, we check what is the difference between them
#I tried to remove the outlier, it didn#t work

```{r Check outlier in model}
imp3.5y%>%
  group_by(clus)%>%
  summarise(sum(cens))
 #PINE has much more events than others

imp3.5y%>%
  filter(cens==1)%>%
  group_by(clus)%>%
  summarise(min(agebl),max(agebl),mean(agebl)) #PINE has one patient very young but even after remove it didn't improve,which means more impact the model than just outliers.

imp3.5y%>%
  group_by(clus)%>%
  summarise(min(agebl),max(agebl),mean(agebl),median(agebl)) #Look at the min and max age in groups, actually not that much difference.

ggplot(imp3.5y, aes(x=clus, y=agebl, fill=clus)) + 
    geom_boxplot()


ggplot(imp3.5y[imp3.5y$cens==1,], aes(x=clus, y=agebl, fill=clus)) + 
    geom_boxplot()

#boxplot to see the outlier of events. so in PINE one patient is super young

#----Now we see the follow-up time----

ggplot(imp3.5y, aes(x=clus, y=year, fill=clus)) + 
    geom_boxplot()

ggplot(imp3.5y[imp3.5y$cens==1,], aes(x=clus, y=year, fill=clus)) + 
    geom_boxplot()

#The PINCNICS one very short time in nursing home is because the patient is 96 years old

#----See the predictor-----

ggplot(imp3.5y, aes(x=clus, y=mdsupdrs3.10, fill=clus)) + 
    geom_boxplot()

ggplot(imp3.5y, aes(x=clus, y=hybl, fill=clus)) + 
    geom_boxplot()

```


```{r KM plot by age group}

#20 years a group

agegroup1<-imp3.5y%>%
  filter(agebl<60)

agegroup2<-imp3.5y%>%
  filter(agebl>=60 & agebl<80)

agegroup3<-imp3.5y%>%
  filter(agebl>=80)

KM1<-survfit(Surv(year,cens)~clus,data=agegroup1)
ggsurvplot(KM1,
           ylab="Cumulative probability of institutionalisation",
           xlab="Time to institutionalisation",
           legend="top",
           surv.median.line = "hv",
           fun="event",
           risk.table = F,
           ggtheme = theme_bw(),
           legend.labs=c("CamPalGN","ICICLE","NYPUM","ParkWest","PICNICS","PINE"))


KM2<-survfit(Surv(year,cens)~clus,data=agegroup2)
ggsurvplot(KM2,
           ylab="Cumulative probability of institutionalisation",
           xlab="Time to institutionalisation",
           legend="top",
           surv.median.line = "hv",
           fun="event",
           risk.table = F,
           ggtheme = theme_bw(),
           legend.labs=c("CamPalGN","ICICLE","NYPUM","ParkWest","PICNICS","PINE"))


KM3<-survfit(Surv(year,cens)~clus,data=agegroup3)
ggsurvplot(KM3,
           ylab="Cumulative probability of institutionalisation",
           xlab="Time to institutionalisation",
           legend="top",
           surv.median.line = "hv",
           fun="event",
           risk.table = F,
           ggtheme = theme_bw(),
           legend.labs=c("CamPalGN","ICICLE","NYPUM","ParkWest","PICNICS","PINE"))


KM1
KM2
KM3

#The difference is in age group 60-80, PINE has much more events than others
```


```{r take out PINE outlier and try again}

data5y.6v.out<-data5y.6v[data5y.6v$agebl!=45.8,] #take out the one super young in PINE

#data5y.6v.out<-data5y.6v[data5y.6v$agebl>50.1,] #take out the 10 young outlier in PINE, this one not good

data5y.6v.out%>%
  filter(cens==1)%>%
  summarise(min(agebl),max(agebl),mean(agebl),median(agebl))
  

#----Try to take out the very short follow-up time here----

#data1%>%
#  filter(study=="PINE"&year<0.5)%>%
#  select(study,idpicc,originalid,datediagnosis,datedeath) #1173	P286 this one patients died one month after visit
  
#data5y.6v.out<-data5y.6v[data5y.6v$agebl!=45.8,]

#data5y.6v.out<-data5y.6v.out[data5y.6v.out$idpicc!=1173,] #Take out this very short follow-up cos death reason

#But it doesn't improve 

#----mean calibration----

# Observed
obj.6.out <- summary(survfit(
  Surv(year, cens) ~ 1, 
  data = data5y.6v.out),
  times = 4)  

obs_t.6.out<- 1 - obj.6.out$surv

# Expected

data5y.6v.out$pred<-predict(model6,newdata = data5y.6v.out,type = "survival",times = 4)[[2]]  #survival probabilities

exp_t.6.out <-mean(1-data5y.6v.out$pred) #predicts risk, as 1 - S(t|X)

# Observed / Expected ratio
OE_t.6.out <- obs_t.6.out / exp_t.6.out

OE_summary.6.out <- c(
  "OE" = OE_t.6.out,
  "2.5 %" = OE_t.6.out * exp(-qnorm(1 - alpha / 2) * sqrt(1 / obj.6.out$n.event)),
  "97.5 %" = OE_t.6.out * exp(+qnorm(1 - alpha / 2) * sqrt(1 / obj.6.out$n.event))
)

OE_summary.6.out  #improve from 1.42 to 1.36

#----Recalibration----

data5y.6v.out$risk <-(1-data5y.6v.out$pred) #predicted risk, as 1 - S(t|X),the probabilities of events

data5y.6v.out$risk.cll <- log(-log(1-data5y.6v.out$risk)) #complementary log-log link

#Check location of knots again

data5y.6v.out%>%
  filter(cens==1)%>%  #cens==1 event
  summarise(max(year),min(year)) 

vcal.6.RP.out <- flexsurvspline(Surv(year, cens) ~ risk.cll, data = data5y.6v.out, k=1,bknots = c(log(0.5557837),log(3.978097)),scale = "odds")

#model6.re<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl,data=data5y.6,k=1,bknots = c(log(0.5557837),log(3.978097)),scale = "odds") # Becuase other datasets not change so this model can still use

rcs.mod6<-as.data.frame(basis(model6.re$knots,log(4))) #basis spline
data5y.6v.out$rcs1<-rcs.mod6[,2] #But the PINE data change so here need to change
data5y.6v.out$rcs2<-rcs.mod6[,3]

#Cos the PINE change so the linear predictor need to update here 

des_matr6.out<-as.data.frame(model.matrix(~ age10+sex+mdsupdrs3.10+hybl,data=data5y.6v.out))
des_matr6.out$`(Intercept)` <- NULL
#coef6<-c(model6$coefficients[4],model6$coefficients[5],model6$coefficients[6],model6$coefficients[7]) #Same coef because the development data sets are the same
data5y.6v.out$lp.6.out<- as.vector(as.matrix(des_matr6.out) %*% cbind(coef6))

data5y.6v.out$lp.6.out<-data5y.6v.out$lp.6.out

model6.re$res[c("gamma0", "gamma1", "gamma2"), "est"]

log((1-obj.6.out$surv)/mean(1-data5y.6v.out$pred))

data5y.6v.out$pred.re<-1/(1+exp(-21.016487+0.314297+1.127613*log(4)-1.261545*data5y.6v.out$rcs2+data5y.6v.out$lp.6.out))

(1-obj.6.out$surv)/mean(1-data5y.6v.out$pred.re) #Mean calibration improve
#(1-obj.6.out$surv)/mean(1-data5y.6v.out$pred) improve 1.37 to 1.12

data5y.6v.out$risk.re<-1-data5y.6v.out$pred.re


dat_cal.6.RP.re.out <- cbind.data.frame(
  "obs" = 1 - predict(vcal.6.RP.out,
                      type = "survival",
                      times = 4,
                      newdata = data5y.6v.out)[[2]], #1-s(t=4) to get the refitted model predicted risk
  
  "lower" = 1 - predict(vcal.6.RP.out,
                        type = "survival",
                        conf.int = T,
                        times = 4,
                        newdata = data5y.6v.out)[[4]],
  
  "upper" = 1 - predict(vcal.6.RP.out,
                        type = "survival",
                        conf.int = T,
                        times = 4,
                        newdata = data5y.6v.out)[[3]],
  "pred" = data5y.6v.out$risk.re
)

dat_cal.6.RP.re.out <- dat_cal.6.RP.re.out[order(dat_cal.6.RP.re.out$pred), ]

par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.6.RP.re.out$pred, #x is predicted risk from the 
  y=dat_cal.6.RP.re.out$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model",
  ylab = "Predicted risk from refitted model",  
  bty = "n" #no box
)

lines(dat_cal.6.RP.re.out$pred, 
      dat_cal.6.RP.re.out$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.6.RP.re.out$pred, 
      dat_cal.6.RP.re.out$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("bottomright",
        c("Ideal calibration",
          "Calibration curve based on secondary Royston-Parmar model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.85)

# Numerical measures
absdiff_cph.6.RP.re.out <- abs(dat_cal.6.RP.re.out$pred - dat_cal.6.RP.re.out$obs)

numsum_cph.6.RP.re.out <- c(
  "ICI" = mean(absdiff_cph.6.RP.re.out),
  setNames(quantile(absdiff_cph.6.RP.re.out, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.6.RP.re.out)
)
numsum_cph.6.RP.re.out

```

```{r Take out PINE to build model}

model.PINE<-flexsurvspline(Surv(year,cens)~age10+sex+mdsupdrs3.10+hybl,data=data5y.6v,k=1,bknots = c(log(0.5557837),log(3.978097)),scale = "odds")

data5y.6v$pred<-predict(model.PINE,data = data5y.6v,type = "survival",times=4)[[2]]

data5y.6v$risk <-(1-data5y.6v$pred) #predicted risk, as 1 - S(t|X),the probabilities of events

data5y.6v$risk.cll <- log(-log(1-data5y.6v$risk)) #complementary log-log link

#Check location of knots again

data5y.6v%>%
  filter(cens==1)%>%  #cens==1 event
  summarise(max(year),min(year)) 


vcal.6.RP <- flexsurvspline(Surv(year, cens) ~ risk.cll, data = data5y.6v, k=1,bknots = c(log(0.5557837),log(3.978097)),scale = "odds")

dat_cal.6.RP <- cbind.data.frame(
  "obs" = 1 - predict(vcal.6.RP,
                      type = "survival",
                      times = 4,
                      newdata = data5y.6v)[[2]], #1-s(t=5) to get the refitted model predicted risk
  
  "lower" = 1 - predict(vcal.6.RP,
                        type = "survival",
                        conf.int = T,
                        times = 4,
                        newdata = data5y.6v)[[4]],
  
  "upper" = 1 - predict(vcal.6.RP,
                        type = "survival",
                        conf.int = T,
                        times = 4,
                        newdata = data5y.6v)[[3]],
  "pred" = data5y.6v$risk
)



dat_cal.6.RP <- dat_cal.6.RP[order(dat_cal.6.RP$pred), ]

par(xaxs = "i", yaxs = "i", las = 1)
plot(
  x=dat_cal.6.RP$pred, #x is predicted risk from the 
  y=dat_cal.6.RP$obs,
  type = "l", 
  lty = 1, 
  xlim = c(0, 1),
  ylim = c(0, 1), 
  lwd = 2,
  xlab = "Predicted risk from developed model",
  ylab = "Predicted risk from refitted model",  
  bty = "n" #no box
)

lines(dat_cal.6.RP$pred, 
      dat_cal.6.RP$lower, 
      type = "l", 
      lty = 2, 
      lwd = 2)
lines(dat_cal.6.RP$pred, 
      dat_cal.6.RP$upper,
      type = "l", 
      lty = 2, 
      lwd = 2)
abline(0, 1, lwd = 2, lty = 2, col = 2)
legend("bottomright",
        c("Ideal calibration",
          "Calibration curve based on secondary Royston-Parmar model",
          "95% confidence interval"),
        col = c(2, 1, 1),
        lty = c(2, 1, 2),
        lwd = c(2, 2, 2),
        bty = "n",
        cex = 0.85)

# Numerical measures
absdiff_cph.6.RP <- abs(dat_cal.6.RP$pred - dat_cal.6.RP$obs)

numsum_cph.6.RP <- c(
  "ICI" = mean(absdiff_cph.6.RP),
  setNames(quantile(absdiff_cph.6.RP, c(0.5, 0.9)), c("E50", "E90")),
  "Emax" = max(absdiff_cph.6.RP)
)
numsum_cph.6.RP

```


